import { Link } from 'react-router-dom';
import { NutritionBooking, NutritionFAQ, NutritionPhoto } from '../shared/NutritionUI';
import { nutritionPath } from '../shared/nutrition-images';
import { nutritionFaq } from '../shared/nutrition-types';
import { content } from './data/content';
import { ModelLink, NutritionLayout } from './NutritionLayout';
export default function NutricionistaModel05Page() {
    return <NutritionLayout>
 <section className="nc-hero"><div className="ni-wrap nc-hero-grid"><div><span className="ni-eyebrow">Nutrição clínica / Atenção individual</span><h1>Ciência aplicada<br /><em>à sua saúde.</em></h1><p>Uma proposta de acompanhamento com escuta, avaliação individual e clareza sobre cada etapa do cuidado.</p><div className="ni-actions"><ModelLink /><ModelLink page="atendimentos" outline>Conhecer as áreas</ModelLink></div><div className="nc-hero-label"><span>01 / AVALIAÇÃO</span><span>02 / PLANEJAMENTO</span><span>03 / ACOMPANHAMENTO</span></div></div><NutritionPhoto image={content.hero} alt="Profissional ilustrativo com tablet em ambiente de nutrição" eager/></div></section>
 <div className="ni-wrap ni-strip"><span>Escuta e atenção individual</span><span>Online e presencial</span><span>Planejamento conversado</span><span>Respeito à sua história</span></div>
 <section className="ni-section model-services"><div className="ni-wrap"><div className="ni-heading"><div><span className="ni-eyebrow">Áreas de atendimento</span><h2>Áreas de acompanhamento.</h2></div><ModelLink page="atendimentos" outline>Explore a proposta clínica</ModelLink></div><div className="ni-services">{content.services.map((item, index) => <Link className="ni-service" key={item.slug} to={nutritionPath(content.model, 'atendimentos/' + item.slug)}><NutritionPhoto image={item.image} alt={item.name + ' — fotografia ilustrativa'}/><div><span className="ni-eyebrow">0{index + 1} / {item.category}</span><h3>{item.name}</h3><p>{item.text}</p><span className="ni-text-link">Conhecer →</span></div></Link>)}</div></div></section>
 <section className="ni-section nc-method"><div className="ni-wrap"><span className="ni-eyebrow">01 / Processo de cuidado</span><h2>Clareza do primeiro encontro<br /><em>ao acompanhamento.</em></h2><ol className="ni-journey">{content.journey.map((title, index) => <li key={title}><span>0{index + 1}</span><h3>{title}</h3><p>Uma etapa planejada individualmente, com espaço para perguntas.</p></li>)}</ol><ModelLink page="como-funciona" outline>Conhecer o processo</ModelLink></div></section><section className="ni-section"><div className="ni-wrap nc-professional" data-reveal><NutritionPhoto image={content.profile} alt="Profissional ilustrativo em consultório de nutrição"/><div><span className="ni-eyebrow">02 / A abordagem</span><h2>Um olhar clínico.<br /><em>Uma escuta humana.</em></h2><p>{content.about}</p><dl className="nc-credentials"><dt>Profissional</dt><dd>Nome a configurar</dd><dt>Registro no CRN</dt><dd>A configurar</dd><dt>Formação</dt><dd>A configurar</dd></dl><ModelLink page="sobre">Conheça a proposta</ModelLink></div></div></section><section className="ni-section nc-light"><div className="ni-wrap ni-split"><div><span className="ni-eyebrow">03 / Avaliação individual</span><h2>Informação, contexto<br /><em>e próximos passos.</em></h2><p>Uma conversa para compreender a sua rotina. Sem prescrição, interpretação de exames ou indicação automática neste site.</p><ModelLink page="como-funciona" outline>Como é o atendimento</ModelLink></div><NutritionPhoto image={content.consultation} alt="Consulta ilustrativa com planejamento individual"/></div></section>
 <section className="ni-section model-journal"><div className="ni-wrap"><div className="ni-heading"><div><span className="ni-eyebrow">Leituras para o seu momento</span><h2>Um espaço para refletir.</h2></div><ModelLink page="conteudos" outline>Todas as leituras</ModelLink></div><div className="ni-journal">{content.articles.slice(0, 2).map(article => <article key={article.slug}><Link to={nutritionPath(content.model, 'conteudos/' + article.slug)}><NutritionPhoto image={article.image} alt={article.title}/><span className="ni-eyebrow">{article.category}</span><h3>{article.title}</h3><p>{article.text}</p><span className="ni-text-link">Ler conteúdo →</span></Link></article>)}</div></div></section>
 <section className="ni-section model-faq"><div className="ni-wrap ni-split"><div><span className="ni-eyebrow">Antes de começar</span><h2>Uma conversa também tira dúvidas.</h2><p>Conheça a proposta de atendimento e como explorar esta experiência.</p><ModelLink page="como-funciona" outline>Como funciona</ModelLink></div><div>{nutritionFaq.map(item => <NutritionFAQ key={item.question} {...item}/>)}</div></div></section>
 <section className="ni-section model-booking"><div className="ni-wrap ni-booking-grid"><div><span className="ni-eyebrow">Seu próximo encontro</span><h2>Vamos conhecer o seu momento?</h2><p>Uma solicitação demonstrativa para experimentar o agendamento. Sem envio de dados ou reserva.</p><p className="ni-note">Use apenas dados fictícios e preferências de contato.</p></div><NutritionBooking model={content.model} services={content.services}/></div></section>
 <section className="ni-section model-contact"><div className="ni-wrap ni-split"><NutritionPhoto image={content.room} alt="Ambiente ilustrativo de consultório de nutrição"/><div><span className="ni-eyebrow">Online e presencial / Modalidades demonstrativas</span><h2>O cuidado começa na chegada.</h2><p>Endereço, horários e canais de atendimento a configurar.</p><ModelLink page="contato" outline>Conheça o contato</ModelLink></div></div></section>
 <section className="ni-closing"><div className="ni-wrap"><span className="ni-eyebrow">Uma conversa. Um próximo cuidado.</span><h2>{content.tagline}</h2><ModelLink /></div></section>
 </NutritionLayout>;
}
