import { Link } from 'react-router-dom';
import { NutritionBooking, NutritionFAQ, NutritionPhoto } from '../shared/NutritionUI';
import { nutritionPath } from '../shared/nutrition-images';
import { nutritionFaq } from '../shared/nutrition-types';
import { content } from './data/content';
import { ModelLink, NutritionLayout } from './NutritionLayout';
export default function NutricionistaModel02Page() {
    return <NutritionLayout>
 <section className="mn-hero"><NutritionPhoto image={content.hero} alt="Mesa ilustrativa de alimentos frescos para Maison Nutrition" eager sizes="100vw"/><div className="ni-wrap"><span className="ni-eyebrow">Private nutrition / Uma atenção pessoal</span><h1>A arte de nutrir<br /><em>o seu melhor.</em></h1><p>Tempo para conhecer sua história. Cuidado para construir uma experiência que tenha a sua medida.</p><div className="ni-actions"><ModelLink /><ModelLink page="sobre" outline>Descubra a Maison</ModelLink></div><div className="mn-hero-bottom"><span>NUTRITION, PERSONALLY CONSIDERED.</span><span>01 / UMA PRIMEIRA CONVERSA</span></div></div></section>
 <div className="ni-wrap ni-strip"><span>Escuta e atenção individual</span><span>Online e presencial</span><span>Planejamento conversado</span><span>Respeito à sua história</span></div>
 <section className="ni-section model-services"><div className="ni-wrap"><div className="ni-heading"><div><span className="ni-eyebrow">Áreas de atendimento</span><h2>Possibilidades, pessoalmente consideradas.</h2></div><ModelLink page="atendimentos" outline>Explore a seleção</ModelLink></div><div className="ni-services">{content.services.map((item, index) => <Link className="ni-service" key={item.slug} to={nutritionPath(content.model, 'atendimentos/' + item.slug)}><NutritionPhoto image={item.image} alt={item.name + ' — fotografia ilustrativa'}/><div><span className="ni-eyebrow">0{index + 1} / {item.category}</span><h3>{item.name}</h3><p>{item.text}</p><span className="ni-text-link">Conhecer →</span></div></Link>)}</div></div></section>
 <section className="ni-section"><div className="ni-wrap mn-manifesto" data-reveal><span className="ni-eyebrow">01 / The personal approach</span><h2>Nutrir é também<br /><em>dar atenção.</em></h2><div><p>{content.about}</p><p>Uma experiência particular começa por compreender a pessoa, seu contexto e suas prioridades.</p><ModelLink page="sobre" outline>Conheça nossa intenção</ModelLink></div></div></section><section className="ni-section mn-olive"><div className="ni-wrap ni-split"><NutritionPhoto image={content.profile} alt="Retrato ilustrativo da proposta Maison Nutrition"/><div><span className="ni-eyebrow">02 / Seu primeiro encontro</span><h2>Tempo para ouvir.<br /><em>Presença para cuidar.</em></h2><p>Nome do profissional, formação e CRN serão apresentados ao personalizar este modelo.</p><ModelLink page="sobre">A abordagem pessoal</ModelLink></div></div></section><section className="ni-section"><div className="ni-wrap mn-food"><div><span className="ni-eyebrow">03 / Everyday, considered</span><h2>Uma rotina.<br /><em>A sua medida.</em></h2><p>Preferências, contexto e tempo. O planejamento começa na conversa sobre a vida que você vive.</p><ModelLink page="como-funciona" outline>Explore a experiência</ModelLink></div><NutritionPhoto image={content.food} alt="Composição gastronômica ilustrativa de salmão e quinoa"/></div></section><section className="mn-consult"><NutritionPhoto image={content.consultation} alt="Consulta particular ilustrativa de nutrição"/><div className="ni-wrap"><span className="ni-eyebrow">04 / Private consultation</span><h2>Um encontro.<br /><em>Inteiramente seu.</em></h2><ModelLink page="como-funciona">Conheça o acompanhamento</ModelLink></div></section>
 <section className="ni-section model-journal"><div className="ni-wrap"><div className="ni-heading"><div><span className="ni-eyebrow">Leituras para o seu momento</span><h2>Um espaço para refletir.</h2></div><ModelLink page="conteudos" outline>Todas as leituras</ModelLink></div><div className="ni-journal">{content.articles.slice(0, 2).map(article => <article key={article.slug}><Link to={nutritionPath(content.model, 'conteudos/' + article.slug)}><NutritionPhoto image={article.image} alt={article.title}/><span className="ni-eyebrow">{article.category}</span><h3>{article.title}</h3><p>{article.text}</p><span className="ni-text-link">Ler conteúdo →</span></Link></article>)}</div></div></section>
 <section className="ni-section model-faq"><div className="ni-wrap ni-split"><div><span className="ni-eyebrow">Antes de começar</span><h2>Uma conversa também tira dúvidas.</h2><p>Conheça a proposta de atendimento e como explorar esta experiência.</p><ModelLink page="como-funciona" outline>Como funciona</ModelLink></div><div>{nutritionFaq.map(item => <NutritionFAQ key={item.question} {...item}/>)}</div></div></section>
 <section className="ni-section model-booking"><div className="ni-wrap ni-booking-grid"><div><span className="ni-eyebrow">Seu próximo encontro</span><h2>Seu tempo. Seu cuidado.</h2><p>Uma solicitação demonstrativa para experimentar o agendamento. Sem envio de dados ou reserva.</p><p className="ni-note">Use apenas dados fictícios e preferências de contato.</p></div><NutritionBooking model={content.model} services={content.services}/></div></section>
 <section className="ni-section model-contact"><div className="ni-wrap ni-split"><NutritionPhoto image={content.room} alt="Ambiente ilustrativo de consultório de nutrição"/><div><span className="ni-eyebrow">Online e presencial / Modalidades demonstrativas</span><h2>O cuidado começa na chegada.</h2><p>Endereço, horários e canais de atendimento a configurar.</p><ModelLink page="contato" outline>Conheça o contato</ModelLink></div></div></section>
 <section className="ni-closing"><div className="ni-wrap"><span className="ni-eyebrow">Uma conversa. Um próximo cuidado.</span><h2>{content.tagline}</h2><ModelLink /></div></section>
 </NutritionLayout>;
}
