import { Link } from 'react-router-dom'
import { BeautyAccordion, BeautyBookingForm, BeautyPhoto } from '../shared/BeautyInteractions'
import { beautyFaq, beautyTreatments } from '../shared/beauty-data'
import { SkinPanel, TreatmentTile } from '../shared/BeautyTools'
import { NeoLayout, NeoLink } from './NeoLayout'
export default function EsteticaBelezaModel04Page() {
  return <NeoLayout><section className="neo-hero"><div className="neo-wrap neo-hero-grid"><div><span className="bt-eyebrow">Human care. Digital perspective.</span><h1>Tecnologia<br />aplicada à sua<br /><em>melhor versão.</em></h1><p>Uma experiência conectada. Recursos contemporâneos, avaliação individual e clareza para escolher.</p><NeoLink page="skin-scan">Explore o skin scan</NeoLink><div className="neo-status"><i />EXPERIÊNCIA DIGITAL / DEMONSTRATIVA</div></div><div className="neo-scan-portrait"><BeautyPhoto image="evaluation" alt="Análise facial ilustrativa com equipamento" eager /><div className="neo-crosshair" aria-hidden="true" /><span>NEO / SKIN SCAN<br />01 — OBSERVAR<br />02 — COMPREENDER<br />03 — CONVERSAR</span></div></div></section>
    <div className="neo-wrap neo-strip">{[['01', 'Avaliação individual'], ['02', 'Recursos contemporâneos'], ['03', 'Planejamento conversado'], ['04', 'Acompanhamento']].map(([number, text]) => <div key={number}><strong>{number}</strong><span>{text}</span></div>)}</div>
    <section className="neo-section"><div className="neo-wrap neo-diagnosis" data-reveal><div><span className="bt-eyebrow">01 / Skin intelligence</span><h2>O diagnóstico começa<br /><em>por uma conversa.</em></h2><p>Explore as etapas de uma análise digital. O painel é ilustrativo e não realiza diagnóstico.</p><NeoLink page="skin-scan">Abrir experiência demonstrativa</NeoLink></div><SkinPanel technical /></div></section>
    <section className="neo-section neo-ice"><div className="neo-wrap"><span className="bt-eyebrow">02 / Technology suite</span><h2>Recursos avançados.<br /><em>Decisões humanas.</em></h2><div className="neo-equipment">{[{ image: 'equipment' as const, name: 'Estrutura tecnológica' }, { image: 'technology' as const, name: 'Recursos de avaliação' }].map((item, index) => <Link key={item.name} to="/estetica-beleza/modelo-04/equipamentos"><BeautyPhoto image={item.image} alt={item.name} /><div><span>DEVICE / 0{index + 1}</span><h3>{item.name}</h3><p>Conhecer possibilidades e limites faz parte do planejamento.</p></div></Link>)}</div></div></section>
    <section className="neo-section"><div className="neo-wrap"><span className="bt-eyebrow">03 / Connected journey</span><h2>O cuidado tem<br /><em>um caminho.</em></h2><div className="neo-flow">{['Escuta', 'Avaliação', 'Planejamento', 'Continuidade'].map((item, index) => <Link key={item} to="/estetica-beleza/modelo-04/protocolos"><span>STEP 0{index + 1}</span><h3>{item}</h3><span>Explore a etapa ↗</span></Link>)}</div></div></section>
    <section className="neo-section neo-ice"><div className="neo-wrap"><span className="bt-eyebrow">04 / Treatment index</span><h2>Conheça as<br /><em>possibilidades.</em></h2><div className="neo-catalog">{[beautyTreatments[3], beautyTreatments[0], beautyTreatments[2]].map((item, index) => <TreatmentTile key={item.slug} item={item} index={index} model="04" />)}</div><NeoLink page="tratamentos">Todo o catálogo</NeoLink></div></section>
    <section className="neo-section"><div className="neo-wrap neo-team" data-reveal><BeautyPhoto image="team" alt="Equipe fictícia em ambiente de clínica" /><div><span className="bt-eyebrow">05 / Human expertise</span><h2>Por trás de cada recurso.<br /><em>Pessoas.</em></h2><p>Um time ilustrativo que representa uma proposta de atendimento individual e próximo.</p><NeoLink page="profissionais">Conhecer a equipe</NeoLink><p className="bi-note">Perfis e registros fictícios.</p></div></div></section>
    <section className="neo-section neo-ice"><div className="neo-wrap neo-book"><div><span className="bt-eyebrow">06 / Next step</span><h2>Comece pela<br /><em>primeira conversa.</em></h2><p>Explore uma solicitação em três passos. Sem reserva ou envio de dados.</p>{beautyFaq.slice(3, 5).map(item => <BeautyAccordion key={item.question} {...item} />)}</div><BeautyBookingForm steps homePath="/estetica-beleza/modelo-04" /></div></section>
  </NeoLayout>
}
