import { Link } from 'react-router-dom';
import { NutritionBooking, NutritionFAQ, NutritionPhoto } from '../shared/NutritionUI';
import { nutritionPath } from '../shared/nutrition-images';
import { nutritionFaq } from '../shared/nutrition-types';
import { content } from './data/content';
import { ModelLink, NutritionLayout } from './NutritionLayout';
export default function NutricionistaModel06Page() {
    return <NutritionLayout>
 <section className="fn-hero"><div className="ni-wrap fn-masthead"><span>NUTRIÇÃO / UM OLHAR ESSENCIAL</span><h1>O essencial<br />para se <em>sentir bem.</em></h1><div><p>Menos ruído. Mais presença.<br />Um cuidado com espaço para você.</p><ModelLink /></div></div><NutritionPhoto image={content.hero} alt="Natureza morta ilustrativa de grãos e ingredientes" eager sizes="100vw"/><div className="ni-wrap fn-hero-caption"><span>01 / ALIMENTAÇÃO. ROTINA. PRESENÇA.</span><ModelLink page="sobre" outline>A filosofia Forma</ModelLink></div></section>
 <div className="ni-wrap ni-strip"><span>Escuta e atenção individual</span><span>Online e presencial</span><span>Planejamento conversado</span><span>Respeito à sua história</span></div>
 <section className="ni-section model-services"><div className="ni-wrap"><div className="ni-heading"><div><span className="ni-eyebrow">Áreas de atendimento</span><h2>Quatro pontos de partida.</h2></div><ModelLink page="atendimentos" outline>Atendimentos</ModelLink></div><div className="ni-services">{content.services.map((item, index) => <Link className="ni-service" key={item.slug} to={nutritionPath(content.model, 'atendimentos/' + item.slug)}><NutritionPhoto image={item.image} alt={item.name + ' — fotografia ilustrativa'}/><div><span className="ni-eyebrow">0{index + 1} / {item.category}</span><h3>{item.name}</h3><p>{item.text}</p><span className="ni-text-link">Conhecer →</span></div></Link>)}</div></div></section>
 <section className="ni-section"><div className="ni-wrap fn-manifesto" data-reveal><span className="ni-eyebrow">02 / A filosofia</span><h2>O cuidado<br />não precisa<br /><em>de excessos.</em></h2><div><p>{content.about}</p><ModelLink page="sobre" outline>Um olhar mais próximo</ModelLink></div></div></section><section className="fn-food"><NutritionPhoto image={content.food} alt="Café da manhã ilustrativo em uma composição rústica" sizes="100vw"/><div className="ni-wrap"><span className="ni-eyebrow">03 / A vida ao redor da mesa</span><h2>Tempo.<br />Contexto.<br /><em>Presença.</em></h2><ModelLink page="conteudos" outline>Notas sobre a rotina</ModelLink></div></section><section className="ni-section"><div className="ni-wrap fn-profile"><div><span className="ni-eyebrow">04 / Um olhar pessoal</span><h2>A escuta<br />vem <em>primeiro.</em></h2><p>Um retrato da proposta Forma. Nome, formação e CRN a configurar.</p><ModelLink page="sobre" outline>Conheça a abordagem</ModelLink></div><NutritionPhoto image={content.profile} alt="Retrato ilustrativo de profissional planejando refeições"/></div></section><section className="ni-section fn-soft"><div className="ni-wrap"><span className="ni-eyebrow">05 / O método</span><h2>{content.method}</h2><ol className="ni-journey">{content.journey.map((title, index) => <li key={title}><span>0{index + 1}</span><h3>{title}</h3><p>Um passo compartilhado, com clareza e atenção à sua rotina.</p></li>)}</ol><ModelLink page="como-funciona" outline>Como funciona</ModelLink></div></section>
 <section className="ni-section model-journal"><div className="ni-wrap"><div className="ni-heading"><div><span className="ni-eyebrow">Leituras para o seu momento</span><h2>Notas sobre o essencial.</h2></div><ModelLink page="conteudos" outline>Todas as leituras</ModelLink></div><div className="ni-journal">{content.articles.slice(0, 2).map(article => <article key={article.slug}><Link to={nutritionPath(content.model, 'conteudos/' + article.slug)}><NutritionPhoto image={article.image} alt={article.title}/><span className="ni-eyebrow">{article.category}</span><h3>{article.title}</h3><p>{article.text}</p><span className="ni-text-link">Ler conteúdo →</span></Link></article>)}</div></div></section>
 <section className="ni-section model-faq"><div className="ni-wrap ni-split"><div><span className="ni-eyebrow">Antes de começar</span><h2>Uma conversa também tira dúvidas.</h2><p>Conheça a proposta de atendimento e como explorar esta experiência.</p><ModelLink page="como-funciona" outline>Como funciona</ModelLink></div><div>{nutritionFaq.map(item => <NutritionFAQ key={item.question} {...item}/>)}</div></div></section>
 <section className="ni-section model-booking"><div className="ni-wrap ni-booking-grid"><div><span className="ni-eyebrow">Seu próximo encontro</span><h2>Uma primeira conversa.</h2><p>Uma solicitação demonstrativa para experimentar o agendamento. Sem envio de dados ou reserva.</p><p className="ni-note">Use apenas dados fictícios e preferências de contato.</p></div><NutritionBooking model={content.model} services={content.services}/></div></section>
 <section className="ni-section model-contact"><div className="ni-wrap ni-split"><NutritionPhoto image={content.room} alt="Ambiente ilustrativo de consultório de nutrição"/><div><span className="ni-eyebrow">Online e presencial / Modalidades demonstrativas</span><h2>Um lugar para conversar.</h2><p>Endereço, horários e canais de atendimento a configurar.</p><ModelLink page="contato" outline>Conheça o contato</ModelLink></div></div></section>
 <section className="ni-closing"><div className="ni-wrap"><span className="ni-eyebrow">Uma conversa. Um próximo cuidado.</span><h2>{content.tagline}</h2><ModelLink /></div></section>
 </NutritionLayout>;
}
