import { Link } from 'react-router-dom';
import { NutritionBooking, NutritionFAQ, NutritionPhoto } from '../shared/NutritionUI';
import { nutritionPath } from '../shared/nutrition-images';
import { nutritionFaq } from '../shared/nutrition-types';
import { content } from './data/content';
import { ModelLink, NutritionLayout } from './NutritionLayout';
import { ListeningPanel } from '../shared/NutritionPanels';
export default function NutricionistaModel04Page() {
    return <NutritionLayout>
 <section className="lm-hero"><div className="ni-wrap lm-hero-grid"><div><span className="ni-eyebrow">Uma conversa sem julgamentos</span><h1>Comer bem<br />também é<br /><em>viver bem.</em></h1><p>Menos regras prontas. Mais espaço para a sua história. Um acompanhamento que escuta antes de orientar.</p><div className="ni-actions"><ModelLink /><ModelLink page="sobre" outline>Conheça a LeveMente</ModelLink></div><svg className="lm-doodle" viewBox="0 0 160 65" fill="none" aria-hidden="true"><path d="M5 40q40-45 80-5t70-8M40 5c15 0 20 20 0 29-20-9-15-29 0-29Z" stroke="currentColor" strokeWidth="1.5"/></svg></div><div className="lm-portrait"><NutritionPhoto image={content.hero} alt="Conversa ilustrativa e acolhedora em consulta de nutrição" eager/><span>Seu ritmo<br /><em>também importa.</em></span></div></div></section>
 <div className="ni-wrap ni-strip"><span>Escuta e atenção individual</span><span>Online e presencial</span><span>Planejamento conversado</span><span>Respeito à sua história</span></div>
 <section className="ni-section model-services"><div className="ni-wrap"><div className="ni-heading"><div><span className="ni-eyebrow">Áreas de atendimento</span><h2>Por onde você quer começar?</h2></div><ModelLink page="atendimentos" outline>Conheça as possibilidades</ModelLink></div><div className="ni-services">{content.services.map((item, index) => <Link className="ni-service" key={item.slug} to={nutritionPath(content.model, 'atendimentos/' + item.slug)}><NutritionPhoto image={item.image} alt={item.name + ' — fotografia ilustrativa'}/><div><span className="ni-eyebrow">0{index + 1} / {item.category}</span><h3>{item.name}</h3><p>{item.text}</p><span className="ni-text-link">Conhecer →</span></div></Link>)}</div></div></section>
 <section className="ni-section lm-peach"><div className="ni-wrap lm-listening"><div><span className="ni-eyebrow">Podemos começar assim</span><h2>Você não precisa<br /><em>ter tudo resolvido.</em></h2><p>O primeiro encontro é um espaço para conhecer seu momento e fazer perguntas.</p><ModelLink page="como-funciona" outline>Saiba como é a conversa</ModelLink></div><ListeningPanel /></div></section><section className="ni-section"><div className="ni-wrap ni-split" data-reveal><NutritionPhoto image={content.profile} alt="Retrato ilustrativo da proposta LeveMente"/><div><span className="ni-eyebrow">Um olhar acolhedor</span><h2>O cuidado começa<br /><em>pela escuta.</em></h2><p>{content.about}</p><ModelLink page="sobre">Conheça a abordagem</ModelLink><p className="ni-note">Nome, CRN e trajetória a configurar.</p></div></div></section><section className="ni-section lm-lilac"><div className="ni-wrap"><span className="ni-eyebrow">No seu tempo</span><h2>{content.method}</h2><ol className="ni-journey">{content.journey.map((title, index) => <li key={title}><span>0{index + 1}</span><h3>{title}</h3><p>Uma etapa conversada com atenção à sua história.</p></li>)}</ol><ModelLink page="como-funciona" outline>Explore a jornada</ModelLink></div></section><section className="ni-section"><div className="ni-wrap lm-pause"><NutritionPhoto image={content.food} alt="Tigela ilustrativa de iogurte e frutas"/><div><span className="ni-eyebrow">Uma pausa com presença</span><h2>O seu dia tem<br /><em>muitas histórias.</em></h2><p>Uma proposta que dá espaço à sua rotina, às suas preferências e às suas dúvidas.</p><ModelLink page="conteudos" outline>Uma leitura para hoje</ModelLink></div></div></section>
 <section className="ni-section model-journal"><div className="ni-wrap"><div className="ni-heading"><div><span className="ni-eyebrow">Leituras para o seu momento</span><h2>Um espaço para refletir.</h2></div><ModelLink page="conteudos" outline>Todas as leituras</ModelLink></div><div className="ni-journal">{content.articles.slice(0, 2).map(article => <article key={article.slug}><Link to={nutritionPath(content.model, 'conteudos/' + article.slug)}><NutritionPhoto image={article.image} alt={article.title}/><span className="ni-eyebrow">{article.category}</span><h3>{article.title}</h3><p>{article.text}</p><span className="ni-text-link">Ler conteúdo →</span></Link></article>)}</div></div></section>
 <section className="ni-section model-faq"><div className="ni-wrap ni-split"><div><span className="ni-eyebrow">Antes de começar</span><h2>Sua pergunta tem lugar aqui.</h2><p>Conheça a proposta de atendimento e como explorar esta experiência.</p><ModelLink page="como-funciona" outline>Como funciona</ModelLink></div><div>{nutritionFaq.map(item => <NutritionFAQ key={item.question} {...item}/>)}</div></div></section>
 <section className="ni-section model-booking"><div className="ni-wrap ni-booking-grid"><div><span className="ni-eyebrow">Seu próximo encontro</span><h2>Vamos conhecer o seu momento?</h2><p>Uma solicitação demonstrativa para experimentar o agendamento. Sem envio de dados ou reserva.</p><p className="ni-note">Use apenas dados fictícios e preferências de contato.</p></div><NutritionBooking model={content.model} services={content.services}/></div></section>
 <section className="ni-section model-contact"><div className="ni-wrap ni-split"><NutritionPhoto image={content.room} alt="Ambiente ilustrativo de consultório de nutrição"/><div><span className="ni-eyebrow">Online e presencial / Modalidades demonstrativas</span><h2>O cuidado começa na chegada.</h2><p>Endereço, horários e canais de atendimento a configurar.</p><ModelLink page="contato" outline>Conheça o contato</ModelLink></div></div></section>
 <section className="ni-closing"><div className="ni-wrap"><span className="ni-eyebrow">Uma conversa. Um próximo cuidado.</span><h2>{content.tagline}</h2><ModelLink /></div></section>
 </NutritionLayout>;
}
