import { BeautyBookingForm, BeautyPhoto } from '../shared/BeautyInteractions'
import { beautyTreatments } from '../shared/beauty-data'
import { TreatmentTile } from '../shared/BeautyTools'
import { EliteLayout, EliteLink } from './EliteLayout'
export default function EsteticaBelezaModel08Page() {
  return <EliteLayout><section className="elite-hero"><BeautyPhoto image="reception2" alt="Recepção ilustrativa de clínica particular de estética" eager /><div className="elite-wrap"><span className="bt-eyebrow">Private aesthetics / São Paulo</span><h1>Estética extraordinária.<br /><em>Atendimento<br />excepcional.</em></h1><EliteLink page="concierge">Conheça seu concierge</EliteLink><div className="elite-hero-bottom"><span>A PRIVATE EXPERIENCE.<br />A PERSONAL APPROACH.</span><EliteLink page="experiencia">Descubra a Élite</EliteLink></div></div></section>
    <section className="elite-section"><div className="elite-wrap elite-experience" data-reveal><div><span className="bt-eyebrow">01 / The experience</span><h2>O privilégio<br /><em>de ser ouvida.</em></h2><p>Uma conversa com tempo. Uma chegada tranquila. Discrição, conforto e atenção compõem a proposta Élite.</p><EliteLink page="experiencia">A experiência particular</EliteLink></div><BeautyPhoto image="relaxed" alt="Pausa ilustrativa em um ambiente de spa" /></div></section>
    <section className="elite-consultation"><BeautyPhoto image="privateConsultation" alt="Consulta de cuidado individual em cena ilustrativa" /><div className="elite-wrap"><span className="bt-eyebrow">02 / Private consultation</span><h2>A sua história.<br /><em>O nosso primeiro encontro.</em></h2><EliteLink page="agendamento">Solicite seu momento</EliteLink></div></section>
    <section className="elite-section elite-ivory"><div className="elite-wrap"><div className="elite-heading"><div><span className="bt-eyebrow">03 / Signature treatments</span><h2>Uma seleção.<br /><em>Um cuidado pessoal.</em></h2></div><EliteLink page="tratamentos">Explore a assinatura</EliteLink></div><div className="elite-signature">{[beautyTreatments[0], beautyTreatments[2], beautyTreatments[1]].map((item, index) => <TreatmentTile key={item.slug} item={item} index={index} model="08" />)}</div></div></section>
    <section className="elite-section"><div className="elite-wrap elite-technology" data-reveal><BeautyPhoto image="technology" alt="Recurso tecnológico ilustrativo de estética" /><div><span className="bt-eyebrow">04 / Considered precision</span><h2>Precisão em<br /><em>cada escolha.</em></h2><p>A tecnologia integra o cuidado como recurso. Possibilidades e limites são discutidos em avaliação profissional.</p><EliteLink page="tecnologia">Conheça a proposta</EliteLink></div></div></section>
    <section className="elite-section elite-ivory"><div className="elite-wrap elite-specialist"><div><span className="bt-eyebrow">05 / Your specialist</span><h2>Presença que<br /><em>faz diferença.</em></h2><p>Uma proposta de atendimento próximo e reservado, representada por um perfil fictício.</p><EliteLink page="especialista">Conheça a especialista</EliteLink></div><BeautyPhoto image="professional1" alt="Retrato ilustrativo da especialista Élite" /></div></section>
    <section className="elite-clinic"><BeautyPhoto image="room" alt="Ambiente reservado ilustrativo de spa e estética" /><div className="elite-wrap"><span className="bt-eyebrow">06 / Your private retreat</span><h2>Um lugar.<br /><em>Uma sensação.</em></h2><EliteLink page="clinica">Entre na clínica</EliteLink></div></section>
    <section className="elite-section"><div className="elite-wrap elite-concierge" data-reveal><span className="elite-monogram" aria-hidden="true">É</span><div><span className="bt-eyebrow">07 / Private concierge</span><h2>A atenção começa<br /><em>antes da chegada.</em></h2><p>Do primeiro contato ao seu próximo momento: uma experiência que dá espaço para conversar.</p><EliteLink page="concierge">Conheça o atendimento</EliteLink></div></div></section>
    <section className="elite-section elite-ivory"><div className="elite-wrap elite-book"><div><span className="bt-eyebrow">Private booking</span><h2>Um momento.<br /><em>Inteiramente seu.</em></h2><BeautyPhoto image="booking" alt="Solicitação ilustrativa de atendimento particular pelo celular" /></div><BeautyBookingForm steps homePath="/estetica-beleza/modelo-08" /></div></section>
  </EliteLayout>
}
