import { useState } from 'react'
import { Link } from 'react-router-dom'
import { ArrowRight, ChevronLeft, ChevronRight, Quote } from 'lucide-react'
import { BeautyBookingForm, BeautyPhoto } from '../shared/BeautyInteractions'
import { beautyTreatments, lumierePath } from '../shared/beauty-data'
import { LumiereButton, LumiereHeading, LumiereLayout } from './LumiereLayout'

const reviews = [
  ['Marina S.', 'O ambiente, a atenção e o tempo dedicado à conversa tornaram a experiência especial. Cada detalhe parece pensado para acolher.'],
  ['Beatriz L.', 'Encontrei um espaço reservado para falar sobre minhas expectativas com calma e clareza.'],
  ['Helena P.', 'Um encontro tranquilo, com atenção à minha história. A experiência começa na forma de receber.'],
]
export default function EsteticaBelezaModel02Page() {
  const [review, setReview] = useState(0)
  return <LumiereLayout>
    <section className="lm-home-hero"><BeautyPhoto image="premiumHero" alt="Retrato ilustrativo da experiência Lumière Aesthetic" eager /><div className="lm-container"><div className="lm-hero-copy"><span className="lm-label">Private aesthetics · São Paulo</span><h1>A excelência<br />também pode<br /><em>ser sentida.</em></h1><p>Estética particular, tempo e um olhar atento à sua individualidade. Um novo jeito de viver o cuidado.</p><div className="lm-actions"><LumiereButton /><LumiereButton outline to={lumierePath('tratamentos')}>Conhecer tratamentos</LumiereButton></div></div><div className="lm-hero-bottom"><span>BELEZA REAL. PRESENÇA. CUIDADO.</span><Link to={lumierePath('experiencia')}>Descubra a experiência<ArrowRight size={17} /></Link></div></div><svg className="lm-hero-lines" viewBox="0 0 300 600" fill="none" aria-hidden="true"><path d="M290 0Q-90 400 300 590M275 0Q-80 400 300 570M260 0Q-70 400 300 550" stroke="currentColor" /></svg></section>
    <section className="lm-section lm-section--ivory"><div className="lm-container lm-experience" data-reveal><div className="lm-experience-photo"><BeautyPhoto image="reception2" alt="Recepção de uma clínica de estética ilustrativa" /><span>L / EXPERIENCE</span></div><div><span className="lm-label"><b>01</b>The experience</span><h2>Há detalhes<br />que você vê.<br /><em>Outros, você sente.</em></h2><p>Uma chegada tranquila. Uma conversa com tempo. Um espaço que respeita sua privacidade e uma atenção que considera a sua história.</p><p>A Lumière reúne esses detalhes em uma proposta de cuidado particular, contemporânea e pessoal.</p><LumiereButton outline to={lumierePath('experiencia')}>Conheça a Lumière</LumiereButton></div></div></section>
    <section className="lm-section"><div className="lm-container" data-reveal><LumiereHeading number="02" label="Signature treatments" title={<>Um cuidado escolhido.<br /><em>Uma experiência individual.</em></>} to={lumierePath('tratamentos')} link="Todos os tratamentos" /><div className="lm-signature-grid">{[beautyTreatments[0], beautyTreatments[3], beautyTreatments[2]].map((item, index) => <article key={item.slug}><Link to={lumierePath(`tratamentos/${item.slug}`)}><BeautyPhoto image={item.image} alt={`Experiência ilustrativa de ${item.name}`} /><div><span className="lm-label">0{index + 1} / {item.category}</span><h3>{item.name}</h3><p>{item.text}</p><span className="lm-text-link">Explore o tratamento<ArrowRight size={17} /></span></div></Link></article>)}</div></div></section>
    <section className="lm-private"><BeautyPhoto image="privateConsultation" alt="Consulta particular ilustrativa, com escuta e atenção individual" /><div className="lm-container" data-reveal><span className="lm-label">Private consultation</span><h2>Tempo para ouvir.<br /><em>Presença para cuidar.</em></h2><p>Uma conversa reservada sobre suas expectativas. O começo de qualquer planejamento é compreender você.</p><LumiereButton to={lumierePath('consulta-particular')}>Conheça a consulta particular</LumiereButton></div></section>
    <section className="lm-section lm-section--ivory"><div className="lm-container lm-technology" data-reveal><div><span className="lm-label"><b>03</b>Technology & care</span><h2>Tecnologia como recurso.<br /><em>Você como prioridade.</em></h2><p>Recursos contemporâneos fazem parte de uma conversa individual sobre possibilidades, limites e escolhas. O cuidado nunca começa por um equipamento.</p><ul><li>Planejamento individual</li><li>Clareza sobre cada etapa</li><li>Discussão de possibilidades e alternativas</li></ul><LumiereButton outline to={lumierePath('tratamentos/tecnologia-estetica')}>Conhecer nossa proposta</LumiereButton></div><BeautyPhoto image="technology" alt="Equipamento de estética em ambiente ilustrativo" /></div></section>
    <section className="lm-section"><div className="lm-container lm-specialist-home" data-reveal><BeautyPhoto image="professional2" alt="Retrato ilustrativo de especialista de estética" /><div><span className="lm-label"><b>04</b>The specialists</span><h2>O cuidado tem<br /><em>um olhar humano.</em></h2><p>Profissionais que representam uma proposta de estética com escuta, presença e atenção à sua história.</p><LumiereButton outline to={lumierePath('profissionais')}>Conheça os especialistas</LumiereButton><p className="bi-note">Perfis, registros e trajetórias fictícios.</p></div></div></section>
    <section className="lm-section lm-section--ivory"><div className="lm-container" data-reveal><LumiereHeading number="05" label="The clinic" title={<>Um espaço para estar.<br /><em>Um lugar para sentir.</em></>} to={lumierePath('estrutura')} link="Explore a clínica" /><div className="lm-clinic-home">{[{ image: 'reception' as const, title: 'A chegada' }, { image: 'room' as const, title: 'O encontro' }, { image: 'corridor' as const, title: 'Os detalhes' }].map(item => <Link key={item.image} to={lumierePath('estrutura')}><BeautyPhoto image={item.image} alt={`${item.title} — ambiente demonstrativo`} /><span>{item.title}<ArrowRight size={16} /></span></Link>)}</div></div></section>
    <section className="lm-section"><div className="lm-container lm-reviews" data-reveal><div><span className="lm-label"><b>06</b>Histórias de cuidado</span><Quote size={38} strokeWidth={.7} /><div aria-live="polite"><blockquote>“{reviews[review][1]}”</blockquote><strong>{reviews[review][0]}</strong></div><p className="bi-note">Depoimentos demonstrativos, sem avaliações reais.</p><div className="lm-review-controls"><button aria-label="Depoimento anterior" onClick={() => setReview((review + reviews.length - 1) % reviews.length)}><ChevronLeft size={20} /></button><span>0{review + 1} / 0{reviews.length}</span><button aria-label="Próximo depoimento" onClick={() => setReview((review + 1) % reviews.length)}><ChevronRight size={20} /></button></div></div><BeautyPhoto image="mature" alt="Retrato ilustrativo de paciente em um ambiente sereno" /></div></section>
    <section className="lm-section lm-section--ivory"><div className="lm-container lm-private-booking" data-reveal><div><BeautyPhoto image="booking" alt="Solicitação de avaliação pelo celular — cena ilustrativa" /><span>PRIVATE BY NATURE.</span></div><div><span className="lm-label"><b>07</b>Private booking</span><h2>Seu próximo momento.<br /><em>Começa aqui.</em></h2><p>Escolha sua preferência e conheça a experiência de solicitação. Simulação sem envio real de dados.</p><BeautyBookingForm steps homePath={lumierePath()} /></div></div></section>
  </LumiereLayout>
}
