import { useState } from 'react'
import { Link, Navigate, useParams, useSearchParams } from 'react-router-dom'
import { ArrowRight, Mail, MapPin, MessageCircle, Search } from 'lucide-react'
import { BeautyAccordion, BeautyBookingForm, BeautyDialog, BeautyGallery, BeautyPhoto } from '../shared/BeautyInteractions'
import { beautyArticles, beautyFaq, beautySearch, beautyTreatments, lumierePath } from '../shared/beauty-data'
import { LumiereButton, LumiereClosing, LumiereHeading, LumiereInnerHero, LumiereLayout } from './LumiereLayout'

export function LumiereTreatmentsPage() {
  const [search, setSearch] = useState('')
  const [category, setCategory] = useState('Todos')
  const items = beautyTreatments.filter(item => (category === 'Todos' || item.category === category) && beautySearch(`${item.name} ${item.text}`).includes(beautySearch(search)))
  return <LumiereLayout><LumiereInnerHero label="Signature treatments" title={<>Escolhas pessoais.<br /><em>Cuidado com assinatura.</em></>} text="Conheça as experiências de tratamento. Possibilidades, limites e planejamento começam em uma avaliação individual." image="skin" /><section className="lm-section lm-section--ivory"><div className="lm-container"><div className="lm-catalog-tools"><label className="lm-search"><input type="search" aria-label="Buscar tratamentos" value={search} onChange={event => setSearch(event.target.value)} placeholder="Encontre uma experiência" /><Search size={18} /></label><div className="lm-filters" aria-label="Categorias de tratamentos">{['Todos', 'Facial', 'Corporal', 'Tecnologia', 'Pele', 'Bem-estar'].map(item => <button key={item} aria-pressed={item === category} onClick={() => setCategory(item)}>{item}</button>)}</div></div><p className="bi-note" role="status">{items.length} experiência{items.length !== 1 ? 's' : ''} encontrada{items.length !== 1 ? 's' : ''}</p>{items.length ? <div className="lm-treatment-list">{items.map((item, index) => <article key={item.slug}><Link to={lumierePath(`tratamentos/${item.slug}`)}><span className="lm-treatment-number">0{index + 1}</span><BeautyPhoto image={item.image} alt={`Tratamento ilustrativo de ${item.name}`} /><div><span className="lm-label">{item.category}</span><h2>{item.name}</h2><p>{item.text}</p><span className="lm-text-link">Explore este cuidado<ArrowRight size={17} /></span></div></Link></article>)}</div> : <div className="lm-empty"><h2>Nenhuma experiência encontrada.</h2><p>Altere o termo ou a categoria selecionada.</p><button className="lm-button" onClick={() => { setSearch(''); setCategory('Todos') }}>Limpar filtros</button></div>}</div></section><LumiereClosing /></LumiereLayout>
}
export function LumiereTreatmentPage() {
  const { treatmentSlug } = useParams()
  const item = beautyTreatments.find(treatment => treatment.slug === treatmentSlug)
  if (!item) return <Navigate to="/404" replace />
  return <LumiereLayout><LumiereInnerHero label={`Signature · ${item.category}`} title={item.name} text={item.text} image={item.image} /><div className="lm-container lm-treatment-tabs"><a href="#lm-proposta">A proposta</a><a href="#lm-jornada">A experiência</a><a href="#lm-perguntas">Suas perguntas</a></div><section className="lm-section lm-section--ivory" id="lm-proposta"><div className="lm-container lm-treatment-story"><div><span className="lm-label">Um cuidado individual</span><h2>Uma conversa<br /><em>antes de cada escolha.</em></h2><p>{item.detail}</p><p>Este modelo não define condutas, indica procedimentos ou promete resultados. A experiência de cuidado depende de uma avaliação real com profissional habilitado.</p><LumiereButton to={`${lumierePath('agendamento')}?interesse=${item.slug}`} /></div><aside><span className="lm-label">Private consultation</span><h3>Tempo para compreender<br />a sua história.</h3><p>Expectativas, dúvidas e possibilidades discutidas em uma conversa reservada.</p><LumiereButton outline to={lumierePath('consulta-particular')}>Conheça a consulta</LumiereButton></aside></div></section><section className="lm-section" id="lm-jornada"><div className="lm-container"><LumiereHeading label="Uma jornada com presença" title={<>Do primeiro encontro.<br /><em>Ao cuidado contínuo.</em></>} /><div className="lm-timeline">{[['Escuta', 'Compreender suas expectativas.'], ['Avaliação', 'Uma conversa particular.'], ['Planejamento', 'Clareza sobre possibilidades e limites.'], ['Continuidade', 'Próximos passos discutidos com você.']].map(([title, text], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section><section className="lm-section lm-section--ivory" id="lm-perguntas"><div className="lm-container lm-faq-split"><div><span className="lm-label">Antes de começar</span><h2>Perguntas merecem<br /><em>boas conversas.</em></h2><LumiereButton outline to={lumierePath('faq')}>Todas as dúvidas</LumiereButton></div><div>{beautyFaq.slice(0, 3).map(item => <BeautyAccordion key={item.question} {...item} />)}</div></div></section><LumiereClosing /></LumiereLayout>
}
export function LumiereExperiencePage() {
  return <LumiereLayout><LumiereInnerHero label="Private experience" title={<>Mais que estética.<br /><em>Uma experiência completa.</em></>} text="Um cuidado reservado, contemporâneo e próximo. A individualidade está no centro de cada detalhe." image="reception2" /><section className="lm-section lm-section--ivory"><div className="lm-container lm-experience" data-reveal><BeautyPhoto image="relaxed" alt="Uma pausa em um ambiente ilustrativo de spa" /><div><span className="lm-label">A filosofia Lumière</span><h2>Revelar o que<br /><em>torna você única.</em></h2><p>Acreditamos em um cuidado que reconhece a sua história, respeita suas escolhas e dá espaço para conversar com clareza.</p><p>A Lumière Aesthetic representa, neste projeto, uma clínica particular em que tempo, conforto e atenção compõem a experiência.</p><LumiereButton to={lumierePath('consulta-particular')}>Conheça o atendimento</LumiereButton></div></div></section><section className="lm-section"><div className="lm-container"><LumiereHeading label="Nossa assinatura" title={<>O luxo está na presença.<br /><em>E no cuidado com você.</em></>} /><div className="lm-timeline">{[['Tempo', 'Um encontro que dá espaço à sua história.'], ['Privacidade', 'Ambientes reservados, conversas individuais.'], ['Clareza', 'Possibilidades e limites discutidos com atenção.'], ['Continuidade', 'Um vínculo que valoriza o acompanhamento.']].map(([title, text], i) => <article key={title}><span>0{i + 1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section><section className="lm-section lm-section--ivory"><div className="lm-container lm-technology" data-reveal><div><span className="lm-label">Cada detalhe, um convite</span><h2>Um lugar para<br /><em>sentir a diferença.</em></h2><p>Materiais acolhedores, iluminação tranquila e espaços que convidam à presença. A experiência começa antes da consulta.</p><LumiereButton outline to={lumierePath('estrutura')}>Explore a clínica</LumiereButton></div><BeautyPhoto image="room" alt="Sala reservada da clínica demonstrativa" /></div></section><LumiereClosing /></LumiereLayout>
}
export function LumiereConsultationPage() {
  return <LumiereLayout><LumiereInnerHero label="Private consultation" title={<>Uma conversa reservada.<br /><em>Um olhar só para você.</em></>} text="O ponto de partida de um planejamento pessoal: tempo para ouvir sua história e compreender suas expectativas." image="privateConsultation" /><section className="lm-section lm-section--ivory"><div className="lm-container lm-consultation-grid"><div><span className="lm-label">O seu primeiro encontro</span><h2>Antes de escolher.<br /><em>Vamos conversar.</em></h2><p>A consulta particular é apresentada como um espaço de escuta e avaliação individual. Não existe uma indicação de tratamento definida por este site.</p><p>Em um atendimento real, possibilidades, limites, riscos e condições devem ser esclarecidos pelo profissional responsável.</p><LumiereButton /></div><ol>{[['Sua história', 'Conte o que importa para você.'], ['Suas perguntas', 'Dúvidas e expectativas têm espaço.'], ['Suas escolhas', 'Conheça possibilidades e limites.'], ['Seu próximo passo', 'Um planejamento discutido individualmente.']].map(([title, text], index) => <li key={title}><span>0{index + 1}</span><div><h3>{title}</h3><p>{text}</p></div></li>)}</ol></div></section><section className="lm-section"><div className="lm-container lm-specialist-home" data-reveal><BeautyPhoto image="professional2" alt="Retrato de especialista ilustrativa" /><div><span className="lm-label">Um cuidado próximo</span><h2>Técnica e atenção.<br /><em>Presença em cada encontro.</em></h2><p>Conheça os perfis demonstrativos da equipe que representa a experiência Lumière.</p><LumiereButton outline to={lumierePath('profissionais')}>Explore os especialistas</LumiereButton></div></div></section><LumiereClosing /></LumiereLayout>
}
export function LumiereProfessionalsPage() {
  const [selected, setSelected] = useState<string | null>(null)
  return <LumiereLayout><LumiereInnerHero label="The specialists" title={<>O cuidado é pessoal.<br /><em>A presença também.</em></>} text="Uma equipe que representa a proposta de atendimento particular, escuta e atenção da Lumière." image="team" /><section className="lm-section lm-section--ivory"><div className="lm-container"><div className="lm-specialists-list">{[{ name: 'Juliana Martins', image: 'professional2' as const, area: 'Avaliação e estética facial' }, { name: 'Camila Ribeiro', image: 'professional1' as const, area: 'Cuidado estético e bem-estar' }].map((person, index) => <article key={person.name}><BeautyPhoto image={person.image} alt={`Retrato ilustrativo de ${person.name}`} /><div><span className="lm-label">0{index + 1} / {person.area}</span><h2>{person.name}</h2><p>Escuta, atenção individual e uma proposta de cuidado próximo. Perfil e trajetória demonstrativos.</p><small>Registro profissional 000000 · Personagem fictícia</small><button className="lm-text-link" onClick={() => setSelected(person.name)}>Conhecer o perfil<ArrowRight size={17} /></button></div></article>)}</div><p className="bi-note">Retratos ilustrativos. Nenhuma formação, certificação ou registro real é representado neste modelo.</p></div></section><LumiereClosing /><BeautyDialog title={selected || ''} open={selected !== null} onClose={() => setSelected(null)}><p>Um perfil demonstrativo para apresentar a experiência de uma profissional que valoriza a escuta, a comunicação e o cuidado individual.</p><p>Nome, formação e trajetória fictícios, sem vínculo com instituições reais. Registro profissional 000000.</p><LumiereButton /></BeautyDialog></LumiereLayout>
}
export function LumiereClinicPage() {
  return <LumiereLayout><LumiereInnerHero label="The clinic" title={<>Um lugar reservado.<br /><em>Uma sensação de acolhimento.</em></>} text="Ambientes contemporâneos, materiais naturais e atenção à privacidade. Explore a proposta de estrutura da Lumière." image="corridor" /><section className="lm-section lm-section--ivory"><div className="lm-container"><LumiereHeading label="Uma visita com calma" title={<>Cada espaço.<br /><em>Um detalhe do cuidado.</em></>} text="Selecione uma fotografia para conhecer os ambientes ilustrativos." /><BeautyGallery images={[{ image: 'reception', label: 'A recepção' }, { image: 'room', label: 'O espaço reservado' }, { image: 'waiting', label: 'A sala de espera' }, { image: 'equipment', label: 'Os recursos' }, { image: 'detail', label: 'As texturas' }, { image: 'facade', label: 'A chegada' }]} /></div></section><section className="lm-section"><div className="lm-container lm-timeline">{[['Privacidade', 'Consultas e conversas em ambientes reservados.'], ['Conforto', 'Uma atmosfera tranquila e acolhedora.'], ['Acesso', 'Uma proposta que considera diferentes necessidades.'], ['São Paulo', 'Localização ilustrativa na região da Avenida Paulista.']].map(([title, text], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section><LumiereClosing /></LumiereLayout>
}
export function LumiereJournalPage() {
  const [params] = useSearchParams()
  const [selected, setSelected] = useState(() => beautyArticles.find(article => article.slug === params.get('artigo')) || null)
  const [search, setSearch] = useState('')
  const [category, setCategory] = useState('Todos')
  const items = beautyArticles.filter(article => (category === 'Todos' || article.category === category) && beautySearch(`${article.title} ${article.text}`).includes(beautySearch(search)))
  return <LumiereLayout><LumiereInnerHero label="Lumière journal" title={<>Palavras com presença.<br /><em>Leituras com tempo.</em></>} text="Conversas sobre identidade, cuidado e escolhas pessoais. Um espaço editorial para olhar para o seu dia a dia." image="skin" /><section className="lm-section lm-section--ivory"><div className="lm-container"><div className="lm-catalog-tools"><label className="lm-search"><input type="search" value={search} onChange={event => setSearch(event.target.value)} aria-label="Buscar no journal" placeholder="Busque uma leitura" /><Search size={18} /></label><div className="lm-filters">{['Todos', 'Bem-estar', 'Cuidado', 'Essência'].map(item => <button key={item} aria-pressed={category === item} onClick={() => setCategory(item)}>{item}</button>)}</div></div><p className="bi-note" role="status">{items.length} leitura{items.length !== 1 ? 's' : ''} encontrada{items.length !== 1 ? 's' : ''}</p><div className="lm-journal-grid">{items.map((item, index) => <article key={item.slug}><BeautyPhoto image={item.image} alt={`Cena ilustrativa sobre ${item.category}`} /><div><span className="lm-label">0{index + 1} / {item.category}</span><h2>{item.title}</h2><p>{item.text}</p><button className="lm-text-link" onClick={() => setSelected(item)}>Ler conteúdo<ArrowRight size={17} /></button></div></article>)}</div>{!items.length && <div className="lm-empty"><h2>Nenhuma leitura encontrada.</h2><button className="lm-button" onClick={() => { setSearch(''); setCategory('Todos') }}>Limpar filtros</button></div>}</div></section><LumiereClosing /><BeautyDialog title={selected?.title || ''} open={selected !== null} onClose={() => setSelected(null)}>{selected && <><span className="lm-label">{selected.category} · Editorial demonstrativo</span>{selected.paragraphs.map(paragraph => <p key={paragraph}>{paragraph}</p>)}<p className="bi-note">Conteúdo demonstrativo, sem orientação clínica individual.</p><LumiereButton /></>}</BeautyDialog></LumiereLayout>
}
export function LumiereFAQPage() {
  const [search, setSearch] = useState('')
  const items = beautyFaq.filter(item => beautySearch(`${item.question} ${item.answer}`).includes(beautySearch(search)))
  return <LumiereLayout><LumiereInnerHero label="Perguntas frequentes" title={<>Clareza para escolher.<br /><em>Tranquilidade para começar.</em></>} text="Respostas sobre o modelo, a experiência e a solicitação de avaliação demonstrativa." image="consultation" /><section className="lm-section lm-section--ivory"><div className="lm-container lm-faq-split"><div><span className="lm-label">Private concierge</span><h2>O primeiro contato<br /><em>também é cuidado.</em></h2><p>Conheça o nosso contato para explorar a experiência.</p><LumiereButton outline to={lumierePath('contato')}>Fale com o concierge</LumiereButton></div><div><label className="lm-search"><input type="search" aria-label="Buscar uma dúvida" value={search} onChange={event => setSearch(event.target.value)} placeholder="Qual é a sua pergunta?" /><Search size={18} /></label><p className="bi-note" role="status">{items.length} resposta{items.length !== 1 ? 's' : ''}</p>{items.map(item => <BeautyAccordion key={item.question} {...item} />)}{!items.length && <button className="lm-button" onClick={() => setSearch('')}>Limpar busca</button>}</div></div></section></LumiereLayout>
}
export function LumiereContactPage() {
  const [channel, setChannel] = useState<string | null>(null)
  return <LumiereLayout><LumiereInnerHero label="Private concierge" title={<>Uma conversa reservada.<br /><em>Estamos por perto.</em></>} text="Conheça os canais e a proposta de localização da experiência Lumière. Contatos e unidade demonstrativos." image="reception2" /><section className="lm-section lm-section--ivory"><div className="lm-container lm-contact-grid"><div><span className="lm-label">Conheça nosso contato</span><h2>Seu primeiro passo.<br /><em>Com atenção.</em></h2><p>Segunda a sexta, 9h às 18h<br />São Paulo · unidade ilustrativa</p><div className="lm-contact-channels">{[{ label: 'WhatsApp', Icon: MessageCircle, text: '(11) 00000-0000' }, { label: 'E-mail', Icon: Mail, text: 'contato@example.com' }].map(({ label, Icon, text }) => <button key={label} onClick={() => setChannel(label)}><Icon size={23} /><span>{label}<small>{text} · ilustrativo</small></span><ArrowRight size={17} /></button>)}</div><div className="lm-location"><MapPin size={28} /><h3>Região da Avenida Paulista</h3><p>Localização demonstrativa, sem clínica real neste endereço.</p><a className="lm-text-link" href="https://www.google.com/maps/search/?api=1&query=Avenida+Paulista+Sao+Paulo" target="_blank" rel="noreferrer">Explore a região no mapa<ArrowRight size={17} /></a></div></div><div className="lm-booking-panel"><span className="lm-label">Vamos começar?</span><h2>Uma atenção<br /><em>que é sua.</em></h2><p>Conheça o fluxo de solicitação demonstrativa.</p><BeautyBookingForm steps homePath={lumierePath()} /></div></div></section><BeautyDialog title={channel || ''} open={channel !== null} onClose={() => setChannel(null)}><p>Os canais desta clínica fictícia são demonstrativos. Não há envio de mensagem, telefone ou WhatsApp real.</p><p>Ao adaptar este modelo para uma clínica, os contatos podem ser conectados aqui.</p><LumiereButton /></BeautyDialog></LumiereLayout>
}
export function LumiereBookingPage() {
  const [params] = useSearchParams()
  return <LumiereLayout><LumiereInnerHero label="Private booking" title={<>Seu próximo momento.<br /><em>Começa aqui.</em></>} text="Uma solicitação em três passos: seus dados, sua preferência e a revisão. Simulação, sem reserva de consulta real." image="booking" /><section className="lm-section lm-section--ivory"><div className="lm-container lm-booking-grid"><div><span className="lm-label">O cuidado começa na escuta</span><h2>Uma escolha pessoal.<br /><em>Uma conversa com tempo.</em></h2><p>Informe dados fictícios e escolha uma data preferida para experimentar o fluxo. Nenhuma informação será enviada ou salva.</p><LumiereButton outline to={lumierePath('consulta-particular')}>Conheça a consulta</LumiereButton></div><div className="lm-booking-panel"><BeautyBookingForm steps initialInterest={params.get('interesse') || ''} homePath={lumierePath()} /></div></div></section></LumiereLayout>
}
