import { Link } from 'react-router-dom'
import { BeautyAccordion, BeautyBookingForm, BeautyPhoto } from '../shared/BeautyInteractions'
import { beautyFaq, beautyTreatments } from '../shared/beauty-data'
import { TreatmentTile } from '../shared/BeautyTools'
import { SculptLayout, SculptLink } from './SculptLayout'
export default function EsteticaBelezaModel05Page() {
  return <SculptLayout><section className="sculpt-hero"><div className="sculpt-wrap"><span className="bt-eyebrow">Body care, with intention.</span><h1>Seu corpo.<br /><em>Sua história.</em><br />Seu cuidado.</h1><div className="sculpt-hero-bottom"><p>Tecnologia, estratégia e cuidado com o seu corpo. Um caminho que respeita a sua individualidade.</p><SculptLink page="agendamento">Começar minha avaliação</SculptLink></div></div><BeautyPhoto image="body" alt="Tratamento corporal em ambiente ilustrativo" eager /></section>
    <section className="sculpt-section"><div className="sculpt-wrap"><span className="bt-eyebrow">01 / Por onde começar</span><h2>Objetivos pessoais.<br /><em>Sem padrões impostos.</em></h2><div className="sculpt-objectives">{['Conforto', 'Autocuidado', 'Continuidade', 'Uma nova conversa'].map((item, index) => <Link key={item} to="/estetica-beleza/modelo-05/objetivos"><strong>0{index + 1}</strong><h3>{item}</h3><span>Conhecer ↗</span></Link>)}</div></div></section>
    <section className="sculpt-section sculpt-sand"><div className="sculpt-wrap sculpt-evaluation" data-reveal><BeautyPhoto image="consultation" alt="Avaliação ilustrativa em clínica de estética" /><div><span className="bt-eyebrow">02 / A avaliação</span><h2>Antes de um plano.<br /><em>Uma boa conversa.</em></h2><p>Conhecer seu momento, suas expectativas e sua história. O cuidado é construído com você, sem promessas ou atalhos.</p><SculptLink page="agendamento">Conheça a avaliação</SculptLink></div></div></section>
    <section className="sculpt-section"><div className="sculpt-wrap"><span className="bt-eyebrow">03 / Protocolos corporais</span><h2>Um plano que<br /><em>faz espaço para você.</em></h2><div className="sculpt-catalog">{[{ ...beautyTreatments[2], image: 'relaxation' as const }, beautyTreatments[3], beautyTreatments[4]].map((item, index) => <TreatmentTile key={item.slug} item={item} index={index} model="05" />)}</div><SculptLink page="protocolos">Explore as propostas</SculptLink></div></section>
    <section className="sculpt-section sculpt-brown"><div className="sculpt-wrap sculpt-journey"><div><span className="bt-eyebrow">04 / A sua jornada</span><h2>Cuidado não é<br /><em>um ponto de chegada.</em></h2><SculptLink page="jornada">Entenda o acompanhamento</SculptLink></div><ol>{[['Escuta', 'Expectativas têm lugar na conversa.'], ['Avaliação', 'Possibilidades e limites discutidos individualmente.'], ['Planejamento', 'Próximos passos, com clareza.'], ['Continuidade', 'Um percurso que acompanha o seu momento.']].map(([title, text], index) => <li key={title}><span>0{index + 1}</span><div><h3>{title}</h3><p>{text}</p></div></li>)}</ol></div></section>
    <section className="sculpt-section"><div className="sculpt-wrap sculpt-tech" data-reveal><div><span className="bt-eyebrow">05 / Tecnologia</span><h2>Recursos com<br /><em>uma intenção.</em></h2><p>A tecnologia compõe uma proposta de cuidado. A indicação depende de uma avaliação profissional.</p><SculptLink page="tecnologia">Conheça os recursos</SculptLink></div><BeautyPhoto image="technology" alt="Detalhe ilustrativo de equipamento de estética" /></div></section>
    <section className="sculpt-space"><BeautyPhoto image="room" alt="Sala ilustrativa de atendimento reservado" /><div className="sculpt-wrap"><span className="bt-eyebrow">06 / Espaço para cuidar</span><h2>Uma pausa.<br /><em>Um lugar seu.</em></h2><SculptLink page="estrutura">Explore a estrutura</SculptLink></div></section>
    <section className="sculpt-section"><div className="sculpt-wrap sculpt-book"><div><span className="bt-eyebrow">Seu próximo passo</span><h2>O cuidado começa<br /><em>com você.</em></h2><p>Simule uma solicitação de avaliação. Nenhum dado é enviado.</p>{beautyFaq.slice(0, 3).map(item => <BeautyAccordion key={item.question} {...item} />)}</div><BeautyBookingForm homePath="/estetica-beleza/modelo-05" /></div></section>
  </SculptLayout>
}
