export const nutritionImages = {
  portrait: 'Retrato de nutricionista em escritório acolhedor.png',
  specialist: 'Nutricionista em Escritório Wellness.png',
  tablet: 'Profissional de saúde com tablet e alimentos frescos.png',
  plate: 'Nutricionista Apresenta Prato Saudável.png',
  planning: 'Nutricionista Planejando Refeições Saudáveis.png',
  consultation: 'Consulta nutricional acolhedora com alimentos frescos.png',
  listening: 'Consulta de Nutrição e Hábitos Saudáveis.png',
  conversation: 'Consulta de Nutrição e Hábitos Saudáveis (1).png',
  personal: 'Consulta Nutricional com Plano Personalizado.png',
  purpose: 'Consulta Nutricional com Propósito.png',
  plan: 'Consulta Nutricional com Plano Alimentar.png',
  online: 'Consulta Nutricional Online em Ambiente Acolhedor.png',
  call: 'Consulta de Nutrição por Videochamada.png',
  office: 'Consultório de Nutrição Acolhedor e Moderno.png',
  room: 'Consultório de Nutrição Aconchegante.png',
  reception: 'Recepção de Clínica de Nutrição Acolhedora.png',
  table: 'Mesa Colorida de Alimentos Frescos.png',
  ingredients: 'Mesa Vibrante de Ingredientes Saudáveis.png',
  stillLife: 'Natureza em Grãos e Cores.png',
  bowl: 'Bowl colorido de quinoa e frango fresco.png',
  salmon: 'Bowl Saudável de Salmão e Quinoa.png',
  chicken: 'Bowl saudável colorido com frango grelhado.png',
  breakfast: 'Café da Manhã Saudável Rústico.png',
  yogurt: 'Tigela Colorida de Iogurte e Frutas.png',
  vegetables: 'Frescor Colorido na Tábua de Corte.png',
  running: 'Corrida ao pôr do sol à beira d’água.png',
  stretch: 'Alongamento Fitness no Parque ao Amanhecer.png',
  sportsConsult: 'Consulta Nutricional para Ganho Muscular.png',
  assessment: 'Avaliação Nutricional na Academia.png',
  mealPrep: 'Preparo fitness com foco e disciplina.png',
  recovery: 'Pós-treino com proteína e energia.png',
  mindful: 'Momento de Alimentação Consciente.png',
  meditation: 'Meditação e equilíbrio em casa.png',
  morning: 'Rotina de autocuidado e bem-estar matinal.png',
  family: 'Refeição Saudável em Família.png',
  familyCooking: 'Cozinhando Saúde em Família.png',
  kids: 'Nutrição infantil à mesa.png',
  familySnack: 'Família Preparando Lanches Saudáveis.png',
  familyMoment: 'Momento Saudável em Família.png',
  work: 'Planejamento Alimentar Saudável no Trabalho.png',
  hydration: 'Hidratação e hábitos saudáveis em foco.png',
  team: 'Equipe de Nutrição em Ambiente Natural.png',
} as const
export type NutritionImage = keyof typeof nutritionImages
export const nutritionPhoto = (key: NutritionImage, width: 640 | 1280 = 1280) => encodeURI(`/images/nutricionista/optimized/${nutritionImages[key].replace('.png', width === 640 ? '-640.jpg' : '.jpg')}`)
export const nutritionPath = (model: string, page = '') => `/nutricionista/modelo-${model}${page ? `/${page}` : ''}`
