import { Link } from 'react-router-dom';
import { NutritionBooking, NutritionFAQ, NutritionPhoto } from '../shared/NutritionUI';
import { nutritionPath } from '../shared/nutrition-images';
import { nutritionFaq } from '../shared/nutrition-types';
import { content } from './data/content';
import { ModelLink, NutritionLayout } from './NutritionLayout';
export default function NutricionistaModel01Page() {
    return <NutritionLayout>
 <section className="en-hero"><div className="ni-wrap en-hero-grid"><div><span className="ni-eyebrow">Nutrição com presença</span><h1>Nutrição leve<br />para uma vida<br /><em>em equilíbrio.</em></h1><p>Acompanhamento que respeita sua história, suas necessidades e o seu ritmo. Estratégias possíveis para a vida real.</p><div className="ni-actions"><ModelLink /><ModelLink page="como-funciona" outline>Conheça o método</ModelLink></div><span className="en-caption">Escuta · Individualidade · Continuidade</span></div><div className="en-portrait"><NutritionPhoto image={content.hero} alt="Retrato ilustrativo de nutricionista em ambiente acolhedor" eager/><div className="en-bowl"><NutritionPhoto image={content.food} alt="Bowl colorido de alimentos — fotografia ilustrativa"/><span>Comida, rotina<br />e a sua história.</span></div></div></div></section>
 <div className="ni-wrap ni-strip"><span>Escuta e atenção individual</span><span>Online e presencial</span><span>Planejamento conversado</span><span>Respeito à sua história</span></div>
 <section className="ni-section model-services"><div className="ni-wrap"><div className="ni-heading"><div><span className="ni-eyebrow">Áreas de atendimento</span><h2>Um cuidado com a sua medida.</h2></div><ModelLink page="atendimentos" outline>Explore os atendimentos</ModelLink></div><div className="ni-services">{content.services.map((item, index) => <Link className="ni-service" key={item.slug} to={nutritionPath(content.model, 'atendimentos/' + item.slug)}><NutritionPhoto image={item.image} alt={item.name + ' — fotografia ilustrativa'}/><div><span className="ni-eyebrow">0{index + 1} / {item.category}</span><h3>{item.name}</h3><p>{item.text}</p><span className="ni-text-link">Conhecer →</span></div></Link>)}</div></div></section>
 <section className="ni-section en-soft"><div className="ni-wrap ni-split" data-reveal><NutritionPhoto image={content.profile} alt="Retrato ilustrativo da proposta Essenza Nutri"/><div><span className="ni-eyebrow">A nossa essência</span><h2>Antes de orientar.<br /><em>Conhecer você.</em></h2><p>{content.about}</p><p>Alimentação faz parte da rotina, da cultura e dos encontros. Sua história tem lugar em cada conversa.</p><ModelLink page="sobre" outline>Conheça a abordagem</ModelLink><p className="ni-note">Nome, CRN e trajetória do profissional: a configurar.</p></div></div></section><section className="ni-section en-method"><div className="ni-wrap"><span className="ni-eyebrow">Um caminho construído em parceria</span><h2>{content.method}</h2><ol className="ni-journey">{content.journey.map((title, index) => <li key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{['Conhecer sua história e suas prioridades.', 'Conversar sobre possibilidades para sua rotina.', 'Revisitar escolhas e próximos passos.'][index]}</p></li>)}</ol><ModelLink page="como-funciona">Entenda cada etapa</ModelLink></div></section><section className="ni-section"><div className="ni-wrap en-consult" data-reveal><div><span className="ni-eyebrow">Como é o encontro</span><h2>Uma conversa<br /><em>com espaço para você.</em></h2><p>Avaliação e orientações individuais, com tempo para compartilhar expectativas e tirar dúvidas.</p><ModelLink page="como-funciona" outline>Online ou presencial</ModelLink></div><NutritionPhoto image={content.consultation} alt="Cena ilustrativa de consulta nutricional"/></div></section>
 <section className="ni-section model-journal"><div className="ni-wrap"><div className="ni-heading"><div><span className="ni-eyebrow">Leituras para o seu momento</span><h2>Um espaço para refletir.</h2></div><ModelLink page="conteudos" outline>Todas as leituras</ModelLink></div><div className="ni-journal">{content.articles.slice(0, 2).map(article => <article key={article.slug}><Link to={nutritionPath(content.model, 'conteudos/' + article.slug)}><NutritionPhoto image={article.image} alt={article.title}/><span className="ni-eyebrow">{article.category}</span><h3>{article.title}</h3><p>{article.text}</p><span className="ni-text-link">Ler conteúdo →</span></Link></article>)}</div></div></section>
 <section className="ni-section model-faq"><div className="ni-wrap ni-split"><div><span className="ni-eyebrow">Antes de começar</span><h2>Uma conversa também tira dúvidas.</h2><p>Conheça a proposta de atendimento e como explorar esta experiência.</p><ModelLink page="como-funciona" outline>Como funciona</ModelLink></div><div>{nutritionFaq.map(item => <NutritionFAQ key={item.question} {...item}/>)}</div></div></section>
 <section className="ni-section model-booking"><div className="ni-wrap ni-booking-grid"><div><span className="ni-eyebrow">Seu próximo encontro</span><h2>Vamos conhecer o seu momento?</h2><p>Uma solicitação demonstrativa para experimentar o agendamento. Sem envio de dados ou reserva.</p><p className="ni-note">Use apenas dados fictícios e preferências de contato.</p></div><NutritionBooking model={content.model} services={content.services}/></div></section>
 <section className="ni-section model-contact"><div className="ni-wrap ni-split"><NutritionPhoto image={content.room} alt="Ambiente ilustrativo de consultório de nutrição"/><div><span className="ni-eyebrow">Online e presencial / Modalidades demonstrativas</span><h2>O cuidado começa na chegada.</h2><p>Endereço, horários e canais de atendimento a configurar.</p><ModelLink page="contato" outline>Conheça o contato</ModelLink></div></div></section>
 <section className="ni-closing"><div className="ni-wrap"><span className="ni-eyebrow">Uma conversa. Um próximo cuidado.</span><h2>{content.tagline}</h2><ModelLink /></div></section>
 </NutritionLayout>;
}
