import { Link } from 'react-router-dom'
import { BeautyPhoto } from '../shared/BeautyInteractions'
import { beautyArticles } from '../shared/beauty-data'
import { MaisonLayout, MaisonLink } from './MaisonLayout'
export default function EsteticaBelezaModel06Page() {
  return <MaisonLayout><section className="maison-hero"><div className="maison-wrap maison-masthead"><span>ESTHÉTIQUE / SÃO PAULO</span><h1>MAISON<br /><em>BEAUTÉ</em></h1><span>MENOS EXCESSOS.<br />MAIS VOCÊ.</span></div><BeautyPhoto image="naturalHero" alt="Retrato ilustrativo em luz natural para a Maison Beauté" eager /><div className="maison-wrap maison-hero-caption"><span>01 / A beleza de ser</span><MaisonLink page="filosofia">Entre na Maison</MaisonLink></div></section>
    <section className="maison-section"><div className="maison-wrap maison-philosophy" data-reveal><span className="bt-eyebrow">Notre philosophie</span><h2>Há beleza<br />no que é <em>essencial.</em></h2><div><p>Um olhar que respeita a individualidade. Uma conversa com espaço para a sua história. Menos excessos. Mais você.</p><MaisonLink page="filosofia">A nossa filosofia</MaisonLink></div></div></section>
    <section className="maison-treatments">{[{ image: 'facial' as const, title: 'Face.', text: 'Um olhar pessoal sobre o cuidado facial.', slug: 'harmonizacao-facial' }, { image: 'body' as const, title: 'Body.', text: 'Atenção ao corpo, respeito às suas escolhas.', slug: 'cuidado-corporal' }, { image: 'skincare' as const, title: 'Skin.', text: 'Uma experiência que começa pela sua pele.', slug: 'limpeza-de-pele' }].map((item, index) => <Link key={item.slug} to={`/estetica-beleza/modelo-06/tratamentos/${item.slug}`}><BeautyPhoto image={item.image} alt={`${item.title} — atendimento ilustrativo`} /><div><span>0{index + 2} / TREATMENT EDIT</span><h2>{item.title}</h2><p>{item.text}</p><span>Descubra →</span></div></Link>)}</section>
    <section className="maison-section"><div className="maison-wrap maison-professional" data-reveal><div><span className="bt-eyebrow">05 / Un regard</span><h2>O cuidado<br />tem um <em>olhar.</em></h2><p>Presença, escuta e clareza. O perfil ilustrativo que representa a nossa proposta de atendimento.</p><MaisonLink page="profissional">Conheça a profissional</MaisonLink><p className="bi-note">Perfil fictício. Registro 000000.</p></div><BeautyPhoto image="professional2" alt="Profissional ilustrativa em ambiente acolhedor" /></div></section>
    <section className="maison-architecture"><BeautyPhoto image="corridor" alt="Corredor ilustrativo com materiais naturais" /><div className="maison-wrap"><span className="bt-eyebrow">06 / Architecture</span><h2>Luz. Silêncio.<br /><em>Presença.</em></h2><MaisonLink page="arquitetura">Explore o espaço</MaisonLink></div></section>
    <section className="maison-section"><div className="maison-wrap"><div className="maison-journal-heading"><h2>Le Journal.</h2><MaisonLink page="journal">Todas as leituras</MaisonLink></div><div className="maison-journal">{beautyArticles.filter(article => article.image !== 'skin').map(article => <Link key={article.slug} to={`/estetica-beleza/modelo-06/journal?artigo=${article.slug}`}><BeautyPhoto image={article.image} alt={article.title} /><span>{article.category}</span><h3>{article.title}</h3><span>Ler →</span></Link>)}</div></div></section>
    <section className="maison-section maison-end"><div className="maison-wrap"><span className="bt-eyebrow">Un premier rendez-vous</span><h2>Seu tempo.<br /><em>Seu cuidado.</em></h2><MaisonLink page="contato">Vamos conversar</MaisonLink></div></section>
  </MaisonLayout>
}
