import { ArrowRight, Check, Clock3, Mail, MapPin, MessageCircle, Phone } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { specialties } from '../care-data'
import { CareBrand, CareButton, CareModal, CarePhoto, SectionIntro } from './CarePrimitives'

export function Appointment() {
  const [sent, setSent] = useState(false)
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSent(true) }
  return <section className="ec-section ec-appointment" id="agendamento"><div className="ec-container"><div className="ec-appointment-top" data-reveal><div><SectionIntro eyebrow="Vamos cuidar de você" title={<>Agende sua consulta<br />sem complicação.</>}>Escolha a especialidade, informe sua preferência de horário e dê o primeiro passo.</SectionIntro><ul className="ec-checklist">{['Agendamento online','Escolha da especialidade','Horários flexíveis','Confirmação por WhatsApp*'].map(text=><li key={text}><Check size={18} />{text}</li>)}</ul><p className="ec-disclaimer">*Fluxo ilustrativo. Nenhuma mensagem ou confirmação real é enviada.</p></div><CarePhoto image="appointment-phone" alt="Telefone exibindo um exemplo de escolha de especialidade para agendamento" /></div>
    <div className="ec-appointment-form-wrap" data-reveal><div><h3>Seu próximo encontro<br />começa aqui.</h3><p>Preencha os campos para experimentar o agendamento. Esta é uma clínica fictícia: seus dados ficam apenas nesta tela.</p><span className="ec-form-note"><Phone size={20} />(11) 0000-0000 · telefone demonstrativo</span></div><form className="ec-booking-form" onSubmit={submit}><div className="ec-form-grid"><label htmlFor="ec-name">Nome completo<input id="ec-name" name="name" autoComplete="name" placeholder="Como podemos chamar você?" required maxLength={100} /></label><label htmlFor="ec-phone">Telefone<input id="ec-phone" name="phone" type="tel" autoComplete="tel" placeholder="(11) 00000-0000" required /></label><label htmlFor="ec-specialty">Especialidade<select id="ec-specialty" name="specialty" defaultValue="" required><option disabled value="">Selecione uma especialidade</option>{specialties.map(s=><option key={s.name}>{s.name}</option>)}</select></label><label htmlFor="ec-date">Data preferida<input id="ec-date" name="date" type="date" required /></label><label htmlFor="ec-period">Período<select id="ec-period" name="period" defaultValue="Manhã"><option>Manhã</option><option>Tarde</option><option>Noite</option></select></label><button className="ec-button" type="submit">Solicitar agendamento<ArrowRight size={17} /></button></div><small>Formulário demonstrativo. Nenhum dado é transmitido ou armazenado.</small>{sent && <p className="ec-form-success" role="status"><Check size={18} />Agendamento simulado. Não haverá confirmação ou contato real.</p>}</form></div>
  </div></section>
}

export function Location() {
  return <section className="ec-section ec-location" id="contato"><div className="ec-container ec-location-grid" data-reveal><div><SectionIntro eyebrow="Nossa localização" title={<>Estamos em um lugar<br />de fácil acesso.</>}>Perto da sua rotina, com um ambiente tranquilo para cuidar de você.</SectionIntro><address><div><MapPin size={23} /><span>Av. Paulista, 1000 · Bela Vista<br />São Paulo, SP · endereço demonstrativo</span></div><div><Clock3 size={23} /><span>Segunda a sexta: 8h às 20h<br />Sábado: 8h às 14h</span></div><div><Phone size={23} /><span>(11) 0000-0000 · telefone fictício<br />contato@example.com</span></div></address><div className="ec-actions"><CareButton href="https://www.google.com/maps/search/?api=1&query=Avenida+Paulista+1000+Sao+Paulo" secondary>Ver no Google Maps</CareButton><a className="ec-text-link" href="#agendamento"><MessageCircle size={17} />Conversar sobre agendamento</a></div><p className="ec-disclaimer">O mapa externo mostra a região; a clínica e seu endereço são fictícios.</p></div><div className="ec-map" role="img" aria-label="Mapa ilustrativo da região da Avenida Paulista, sem localização real da clínica"><span className="ec-map-park">Área verde</span><span className="ec-map-road ec-map-road--1" /><span className="ec-map-road ec-map-road--2" /><span className="ec-map-road ec-map-road--3" /><span className="ec-map-label">Av. Paulista</span><div className="ec-map-pin"><MapPin size={28} /><strong>Essencial Care<small>Localização ilustrativa</small></strong></div><span className="ec-map-note">Mapa demonstrativo</span></div></div></section>
}

export function FinalCTA() {
  return <section className="ec-final-cta"><div className="ec-container" data-reveal><span className="ec-eyebrow">Sua saúde merece atenção</span><h2>Em cada etapa da vida,<br /><em>conte com cuidado de verdade.</em></h2><CareButton>Agendar consulta</CareButton></div></section>
}

export function CareFooter() {
  const [notice, setNotice] = useState<string | null>(null)
  const legal: Record<string,string> = {
    'Política de Privacidade': 'Este site é uma demonstração. O formulário não transmite nem armazena dados. Informações preenchidas existem apenas no navegador durante a visita. Links externos, como Google Maps, levam a serviços com políticas próprias.',
    'Termos de Uso': 'Nomes, registros, depoimentos, disponibilidade e indicadores são fictícios. O conteúdo apresenta uma landing page e não oferece atendimento médico real nem substitui avaliação profissional.',
    'LGPD': 'Não há coleta por backend, cadastro de pacientes ou envio a serviços externos. Evite inserir dados de saúde ou informações sensíveis nesta demonstração.',
    'Redes sociais': 'Os canais sociais da Essencial Care são demonstrativos. Nenhum perfil externo foi configurado para esta clínica fictícia.',
  }
  return <footer className="ec-footer"><div className="ec-container"><div className="ec-footer-grid"><div><a href="#inicio"><CareBrand /></a><p>Medicina próxima, humana<br />e responsável.</p><button className="ec-text-link" type="button" onClick={()=>setNotice('Redes sociais')}>Conheça nossos canais<ArrowRight size={16} /></button></div><div><h3>Institucional</h3><a href="#sobre">Sobre a clínica</a><a href="#equipe">Nossa equipe</a><a href="#estrutura">Estrutura</a><a href="#contato">Contato</a></div><div><h3>Especialidades</h3>{specialties.map(s=><a key={s.name} href="#especialidades">{s.name}</a>)}</div><div><h3>Conteúdos</h3><a href="#conteudos">Bem-estar</a><a href="#conteudos">Prevenção</a><a href="#conteudos">Nutrição</a><a href="#duvidas">Dúvidas frequentes</a></div><div><h3>Redes sociais</h3><button className="ec-text-link" type="button" onClick={()=>setNotice('Redes sociais')}>Conhe?a nossos canais<ArrowRight size={16} /></button></div><div><h3>Fale conosco</h3><a href="#contato"><Phone size={15} />(11) 0000-0000</a><a href="#contato"><Mail size={15} />contato@example.com</a><span>Seg a sex: 8h às 20h<br />Sáb: 8h às 14h</span><small>Contatos demonstrativos.</small></div></div><div className="ec-footer-bottom"><p>© 2026 Essencial Care · Clínica e dados fictícios.</p><div>{['Política de Privacidade','Termos de Uso','LGPD'].map(label=><button key={label} type="button" onClick={()=>setNotice(label)}>{label}</button>)}</div></div></div><CareModal open={notice !== null} title={notice || 'Informações'} onClose={()=>setNotice(null)}><p>{notice && legal[notice]}</p></CareModal></footer>
}

export function WhatsApp() {
  const [open,setOpen] = useState(false)
  return <><button className="ec-whatsapp" type="button" aria-label="WhatsApp demonstrativo da clínica" title="Fale com a equipe" onClick={()=>setOpen(true)}><MessageCircle size={27} /></button><CareModal open={open} title="Vamos conversar?" onClose={()=>setOpen(false)}><p>Este WhatsApp é demonstrativo. Nenhum número real foi conectado, e nenhuma mensagem será enviada.</p><CareButton onClick={()=>setOpen(false)}>Experimentar agendamento</CareButton></CareModal></>
}
