import { useState } from 'react'
import { Link, Navigate, useParams, useSearchParams } from 'react-router-dom'
import { ArrowRight, Heart, Leaf, Mail, MapPin, MessageCircle, Search, ShieldCheck } from 'lucide-react'
import { BeautyAccordion, BeautyBookingForm, BeautyDialog, BeautyGallery, BeautyPhoto } from '../shared/BeautyInteractions'
import { beautyArticles, beautyFaq, beautySearch, beautyTreatments, essenzaPath } from '../shared/beauty-data'
import { EssenzaButton, EssenzaClosing, EssenzaInnerHero, EssenzaLayout, EssenzaTitle } from './EssenzaLayout'

export function EssenzaTreatmentsPage() {
  const [search, setSearch] = useState('')
  const [category, setCategory] = useState('Todos')
  const items = beautyTreatments.filter(item => (category === 'Todos' || item.category === category) && beautySearch(`${item.name} ${item.text}`).includes(beautySearch(search)))
  return <EssenzaLayout><EssenzaInnerHero label="Nossos tratamentos" title={<>Cuidados para<br /><em>a sua essência.</em></>} text="Conheça diferentes propostas de cuidado. O que faz sentido para você começa por uma avaliação individual." image="wellness" /><section className="en-section"><div className="en-container"><div className="en-catalog-tools"><label className="en-search"><input type="search" aria-label="Buscar tratamentos" placeholder="O que você gostaria de conhecer?" value={search} onChange={event => setSearch(event.target.value)} /><Search size={19} /></label><div className="en-filters" aria-label="Categorias de tratamentos">{['Todos', 'Facial', 'Corporal', 'Pele', 'Tecnologia', 'Bem-estar'].map(item => <button key={item} aria-pressed={item === category} onClick={() => setCategory(item)}>{item}</button>)}</div></div><p className="bi-note" role="status">{items.length} cuidado{items.length !== 1 ? 's' : ''} encontrado{items.length !== 1 ? 's' : ''}</p>{items.length ? <div className="en-treatment-grid en-treatment-grid--catalog">{items.map(item => <article className="en-treatment" key={item.slug}><Link to={essenzaPath(`tratamentos/${item.slug}`)}><BeautyPhoto image={item.image} alt={`Atendimento ilustrativo de ${item.name}`} /><div><span className="en-label">{item.category}</span><h3>{item.name}</h3><p>{item.text}</p><span className="en-link">Conhecer o cuidado<ArrowRight size={16} /></span></div></Link></article>)}</div> : <div className="en-empty" role="status"><Leaf /><h2>Vamos tentar outro cuidado?</h2><p>Nenhum resultado para esses filtros.</p><button className="en-button" onClick={() => { setSearch(''); setCategory('Todos') }}>Limpar filtros</button></div>}</div></section><EssenzaClosing /></EssenzaLayout>
}
export function EssenzaTreatmentPage() {
  const { treatmentSlug } = useParams()
  const item = beautyTreatments.find(treatment => treatment.slug === treatmentSlug)
  if (!item) return <Navigate to="/404" replace />
  return <EssenzaLayout><EssenzaInnerHero label={`Tratamentos · ${item.category}`} title={item.name} text={item.text} image={item.image} /><div className="en-container en-detail-nav"><a href="#en-cuidado">O cuidado</a><a href="#en-processo">Como funciona</a><a href="#en-duvidas">Suas dúvidas</a></div><section className="en-section" id="en-cuidado"><div className="en-container en-detail-grid"><div><span className="en-label">O começo é uma conversa</span><h2>Conhecer você.<br /><em>Antes de escolher.</em></h2><p>{item.detail}</p><p>Textos e tratamentos são demonstrativos. Não há indicação clínica, promessa de resultado ou atendimento real neste site.</p><div className="en-values"><span><Leaf />Individualidade</span><span><ShieldCheck />Clareza</span><span><Heart />Acolhimento</span></div></div><aside className="en-detail-booking"><h3>Reserve um tempo<br />para conversar.</h3><p>Conheça a experiência de avaliação antes de qualquer decisão.</p><EssenzaButton to={`${essenzaPath('agendamento')}?interesse=${item.slug}`} /><EssenzaButton outline to={essenzaPath('contato')}>Fale com a equipe</EssenzaButton></aside></div></section><section className="en-section en-section--cream" id="en-processo"><div className="en-container"><EssenzaTitle label="A sua jornada" title={<>Cada etapa.<br /><em>Com atenção a você.</em></>} /><div className="en-process-grid">{[['Escuta', 'Expectativas e prioridades têm espaço.'], ['Avaliação', 'Uma conversa individual com o profissional.'], ['Planejamento', 'Possibilidades e limites explicados com clareza.'], ['Acompanhamento', 'Um cuidado que valoriza a continuidade.']].map(([title, text], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section><section className="en-section" id="en-duvidas"><div className="en-container en-faq-split"><div><span className="en-label">Podemos esclarecer?</span><h2>Suas perguntas<br /><em>importam.</em></h2><Link className="en-link" to={essenzaPath('faq')}>Todas as dúvidas<ArrowRight size={16} /></Link></div><div>{beautyFaq.slice(0, 3).map(question => <BeautyAccordion key={question.question} {...question} />)}</div></div></section><EssenzaClosing /></EssenzaLayout>
}
export function EssenzaAboutPage() {
  return <EssenzaLayout><EssenzaInnerHero label="Nossa essência" title={<>A sua história.<br /><em>O nosso cuidado.</em></>} text="Uma proposta de estética que começa pela individualidade e valoriza o bem-estar em cada detalhe." image="relaxed" /><section className="en-section"><div className="en-container en-about-story" data-reveal><div><span className="en-label">Estética com propósito</span><h2>Não existe outra<br /><em>pessoa como você.</em></h2><p>A Essenza Natural nasceu, neste projeto demonstrativo, para representar um cuidado que respeita escolhas, ritmos e histórias pessoais.</p><p>Acolher é criar espaço para uma boa conversa. É olhar para as expectativas com clareza e combinar cada etapa com atenção.</p><EssenzaButton /></div><BeautyPhoto image="teamCandid" alt="Conversa ilustrativa da equipe de cuidado" /></div></section><section className="en-philosophy"><div className="en-container"><div><span className="en-label">Nosso compromisso</span><h2>Presença na escuta.<br /><em>Respeito na escolha.</em></h2></div><div><p>Um ambiente tranquilo. Uma conversa transparente. Uma experiência humana, que considera a beleza como parte da sua identidade.</p></div><Leaf size={180} strokeWidth={.4} /></div></section><section className="en-section"><div className="en-container en-process-grid">{[['Sua essência', 'Individualidade como ponto de partida.'], ['Seu tempo', 'Uma experiência calma e reservada.'], ['Sua escolha', 'Clareza para conversar sobre possibilidades.'], ['Seu bem-estar', 'Acolhimento em cada encontro.']].map(([title, text]) => <article key={title}><Leaf size={26} /><h3>{title}</h3><p>{text}</p></article>)}</div></section><EssenzaClosing /></EssenzaLayout>
}
export function EssenzaProfessionalsPage() {
  const [selected, setSelected] = useState<string | null>(null)
  return <EssenzaLayout><EssenzaInnerHero label="Profissionais" title={<>Pessoas que acolhem.<br /><em>Um cuidado próximo.</em></>} text="Uma equipe demonstrativa que representa atenção individual, comunicação clara e respeito à sua história." image="team" /><section className="en-section"><div className="en-container"><EssenzaTitle label="Conheça nossa equipe" title="Técnica e um olhar humano" /><div className="en-professionals-grid">{[{ name: 'Juliana Martins', image: 'professional1' as const, role: 'Estética facial e avaliação' }, { name: 'Camila Ribeiro', image: 'professional2' as const, role: 'Cuidado corporal e bem-estar' }].map(person => <article key={person.name}><BeautyPhoto image={person.image} alt={`Retrato ilustrativo de ${person.name}`} /><div><span className="en-label">{person.role}</span><h3>{person.name}</h3><p>Escuta, acolhimento e cuidado individual.</p><small>Registro profissional 000000 · Perfil fictício</small><button className="en-link" onClick={() => setSelected(person.name)}>Conhecer o perfil<ArrowRight size={17} /></button></div></article>)}</div><p className="bi-note">Nomes, registros e trajetórias fictícios. As fotos são ilustrativas e não representam credenciais reais.</p></div></section><EssenzaClosing /><BeautyDialog title={selected || ''} open={selected !== null} onClose={() => setSelected(null)}><p>Este perfil representa uma profissional com atenção à escuta e ao cuidado individual. Formação, experiência e registro são demonstrativos, sem vínculo com instituição real.</p><p>Registro profissional 000000. Nenhuma avaliação ou procedimento real é oferecido neste site.</p><EssenzaButton /></BeautyDialog></EssenzaLayout>
}
export function EssenzaStructurePage() {
  return <EssenzaLayout><EssenzaInnerHero label="Nossa estrutura" title={<>Acolhimento que<br /><em>também se sente.</em></>} text="Luz natural, texturas acolhedoras e espaços reservados. Um lugar pensado para uma experiência tranquila." image="corridor" /><section className="en-section"><div className="en-container"><EssenzaTitle label="Explore os ambientes" title={<>Um lugar para<br /><em>desacelerar.</em></>} text="Selecione uma fotografia para ampliar e navegar pela galeria ilustrativa." /><BeautyGallery images={[{ image: 'reception', label: 'Recepção acolhedora' }, { image: 'room', label: 'Sala de cuidado' }, { image: 'waiting', label: 'Espera tranquila' }, { image: 'detail', label: 'Detalhes de bem-estar' }]} /></div></section><section className="en-section en-section--cream"><div className="en-container en-process-grid">{[['Conforto', 'Uma proposta de ambiente reservado e acolhedor.'], ['Privacidade', 'Espaço para conversas individuais.'], ['Acesso', 'Circulação e chegada pensadas como parte do cuidado.'], ['Localização', 'São Paulo · localização demonstrativa.']].map(([title, text]) => <article key={title}><Leaf size={26} /><h3>{title}</h3><p>{text}</p></article>)}</div></section><EssenzaClosing /></EssenzaLayout>
}
export function EssenzaContentsPage() {
  const [params] = useSearchParams()
  const [selected, setSelected] = useState(() => beautyArticles.find(item => item.slug === params.get('artigo')) || null)
  const [search, setSearch] = useState('')
  const items = beautyArticles.filter(item => beautySearch(`${item.title} ${item.category} ${item.text}`).includes(beautySearch(search)))
  return <EssenzaLayout><EssenzaInnerHero label="Conteúdos Essenza" title={<>Um olhar para<br /><em>o seu dia a dia.</em></>} text="Leituras sobre identidade, tempo e cuidado. Um espaço editorial demonstrativo, sem orientação clínica individual." image="wellness" /><section className="en-section"><div className="en-container"><label className="en-search"><input type="search" value={search} onChange={event => setSearch(event.target.value)} aria-label="Buscar conteúdos" placeholder="Busque um tema para ler com calma" /><Search size={19} /></label><p className="bi-note" role="status">{items.length} leitura{items.length !== 1 ? 's' : ''} encontrada{items.length !== 1 ? 's' : ''}</p><div className="en-articles">{items.map(item => <article key={item.slug}><BeautyPhoto image={item.image} alt={`Fotografia ilustrativa sobre ${item.category}`} /><span className="en-label">{item.category}</span><h3>{item.title}</h3><p>{item.text}</p><button className="en-link" onClick={() => setSelected(item)}>Ler conteúdo<ArrowRight size={17} /></button></article>)}</div>{!items.length && <div className="en-empty"><h2>Nenhuma leitura encontrada.</h2><button className="en-button" onClick={() => setSearch('')}>Limpar busca</button></div>}</div></section><EssenzaClosing /><BeautyDialog title={selected?.title || ''} open={selected !== null} onClose={() => setSelected(null)}>{selected && <><span className="en-label">{selected.category} · Editorial demonstrativo</span>{selected.paragraphs.map(paragraph => <p key={paragraph}>{paragraph}</p>)}<EssenzaButton /></>}</BeautyDialog></EssenzaLayout>
}
export function EssenzaFAQPage() {
  const [search, setSearch] = useState('')
  const items = beautyFaq.filter(item => beautySearch(`${item.question} ${item.answer}`).includes(beautySearch(search)))
  return <EssenzaLayout><EssenzaInnerHero label="Perguntas frequentes" title={<>Clareza também<br /><em>é cuidado.</em></>} text="Respostas para conhecer o modelo, a experiência e o agendamento demonstrativo." image="consultation" /><section className="en-section"><div className="en-container en-faq-split"><div><h2>Como podemos<br /><em>ajudar?</em></h2><p>Suas perguntas têm espaço aqui.</p><EssenzaButton outline to={essenzaPath('contato')}>Fale com a equipe</EssenzaButton></div><div><label className="en-search"><input type="search" aria-label="Buscar uma dúvida" value={search} onChange={event => setSearch(event.target.value)} placeholder="Busque uma dúvida" /><Search size={19} /></label><p className="bi-note" role="status">{items.length} resposta{items.length !== 1 ? 's' : ''}</p>{items.map(item => <BeautyAccordion key={item.question} {...item} />)}{!items.length && <button className="en-button" onClick={() => setSearch('')}>Limpar busca</button>}</div></div></section></EssenzaLayout>
}
export function EssenzaContactPage() {
  const [channel, setChannel] = useState<string | null>(null)
  return <EssenzaLayout><EssenzaInnerHero label="Contato e localização" title={<>O cuidado começa<br /><em>com uma conversa.</em></>} text="Conheça a proposta de acolhimento da nossa equipe e explore a localização ilustrativa." image="reception2" /><section className="en-section"><div className="en-container en-contact-grid"><div><span className="en-label">Estamos por perto</span><h2>Vamos conversar.</h2><p>Segunda a sexta, 9h às 18h<br />São Paulo · unidade demonstrativa</p><div className="en-contact-channels">{[{ label: 'WhatsApp', Icon: MessageCircle, info: '(11) 00000-0000' }, { label: 'E-mail', Icon: Mail, info: 'contato@example.com' }].map(({ label, Icon, info }) => <button key={label} onClick={() => setChannel(label)}><Icon size={22} /><span><strong>{label}</strong><small>{info} · demonstrativo</small></span><ArrowRight size={17} /></button>)}</div><div className="en-location-card"><MapPin size={28} /><strong>Região da Avenida Paulista</strong><p>Localização ilustrativa, sem unidade real.</p><a className="en-link" href="https://www.google.com/maps/search/?api=1&query=Avenida+Paulista+Sao+Paulo" target="_blank" rel="noreferrer">Explorar a região<ArrowRight size={16} /></a></div></div><div className="en-contact-form"><span className="en-label">Seu primeiro contato</span><h2>Um momento<br />para você.</h2><p>Experimente o formulário com informações fictícias.</p><BeautyBookingForm homePath={essenzaPath()} /></div></div></section><BeautyDialog title={channel || ''} open={channel !== null} onClose={() => setChannel(null)}><p>Este contato é demonstrativo. Não há envio de mensagem, telefone ou atendimento real da Essenza Natural.</p><EssenzaButton /></BeautyDialog></EssenzaLayout>
}
export function EssenzaBookingPage() {
  const [params] = useSearchParams()
  return <EssenzaLayout><EssenzaInnerHero label="Agendamento" title={<>Reserve um tempo.<br /><em>Para a sua essência.</em></>} text="Sua avaliação começa por uma conversa. Experimente a solicitação demonstrativa, sem envio de dados ou reserva real." image="booking" /><section className="en-section"><div className="en-container en-booking-page"><div><span className="en-label">Como começar</span><h2>O primeiro passo<br /><em>é ouvir você.</em></h2><p>Escolha seu interesse e uma data preferida. Nesta demonstração, você verá apenas uma confirmação de simulação.</p><div className="en-values"><span><Heart />Escuta</span><span><Leaf />Individualidade</span><span><ShieldCheck />Privacidade</span></div><Link className="en-link" to={essenzaPath('faq')}>Esclareça suas dúvidas<ArrowRight size={17} /></Link></div><div className="en-contact-form"><BeautyBookingForm initialInterest={params.get('interesse') || ''} homePath={essenzaPath()} /></div></div></section></EssenzaLayout>
}
