import { useState } from 'react'
import { Link } from 'react-router-dom'
import { ArrowRight, ChevronLeft, ChevronRight, Heart, Leaf, Quote, ShieldCheck } from 'lucide-react'
import { BeautyBookingForm, BeautyPhoto } from '../shared/BeautyInteractions'
import { beautyArticles, beautyTreatments, essenzaPath } from '../shared/beauty-data'
import { EssenzaButton, EssenzaLayout, EssenzaTitle } from './EssenzaLayout'

const stories = [
  ['Mariana C.', 'Gostei de encontrar um espaço em que minhas perguntas tiveram tempo e lugar. Me senti acolhida desde a primeira conversa.'],
  ['Ana P.', 'Os pequenos detalhes e a tranquilidade do ambiente fizeram o encontro ser um momento só meu.'],
  ['Clara M.', 'Uma experiência delicada, com clareza e atenção à minha história. O cuidado aparece na forma de ouvir.'],
]
export default function EsteticaBelezaModel01Page() {
  const [story, setStory] = useState(0)
  return <EssenzaLayout>
    <section className="en-home-hero"><div className="en-container en-hero-grid"><div className="en-hero-copy"><span className="en-label">Estética natural · Bem-estar</span><h1>Beleza que<br />respeita a sua<br /><em>essência.</em></h1><p>Um olhar atento para você. Cuidado estético, acolhimento e uma experiência que respeita a sua individualidade.</p><div className="en-actions"><EssenzaButton /><EssenzaButton outline to={essenzaPath('tratamentos')}>Conhecer tratamentos</EssenzaButton></div><div className="en-hero-values"><span><Leaf size={23} strokeWidth={1} />Sua beleza, sua história</span><span><ShieldCheck size={23} strokeWidth={1} />Atenção individual</span></div></div><div className="en-hero-image"><BeautyPhoto image="naturalHero" alt="Retrato ilustrativo de beleza natural em um ambiente acolhedor" eager /><span>O essencial<br /><em>é ser você.</em></span><svg className="en-leaf-art" viewBox="0 0 200 300" fill="none" aria-hidden="true"><path d="M80 290Q120 130 10 10Q170 30 80 290M90 210Q200 130 190 40Q80 80 90 210M84 250Q0 190 5 100Q90 140 84 250" stroke="currentColor" /></svg></div></div></section>
    <section className="en-section"><div className="en-container en-manifesto" data-reveal><BeautyPhoto image="relaxed" alt="Um momento de pausa e acolhimento" /><div><span className="en-label">Nossa essência</span><h2>Cuidar da beleza<br />também é cuidar de<br /><em>como você se sente.</em></h2><p>Uma experiência que começa pela escuta. Acreditamos em um cuidado que respeita sua história, seu ritmo e suas escolhas.</p><div className="en-values"><span><Leaf />Individualidade</span><span><Heart />Bem-estar</span><span><ShieldCheck />Clareza</span></div><Link className="en-link" to={essenzaPath('sobre')}>Conheça nossa filosofia<ArrowRight size={17} /></Link></div></div></section>
    <section className="en-section en-section--cream"><div className="en-container" data-reveal><EssenzaTitle label="Nossos tratamentos" title={<>Diferentes cuidados.<br /><em>A mesma essência.</em></>} to={essenzaPath('tratamentos')} link="Todos os tratamentos" /><div className="en-treatment-grid">{beautyTreatments.slice(0, 4).map(item => <article className="en-treatment" key={item.slug}><Link to={essenzaPath(`tratamentos/${item.slug}`)}><BeautyPhoto image={item.image} alt={`Experiência ilustrativa de ${item.name}`} /><div><span className="en-label">{item.category}</span><h3>{item.name}</h3><p>{item.text}</p><span className="en-link">Conhecer o cuidado<ArrowRight size={16} /></span></div></Link></article>)}</div></div></section>
    <section className="en-philosophy"><div className="en-container" data-reveal><div><span className="en-label">Nossa filosofia</span><h2>Beleza natural.<br /><em>Cuidado individual.</em></h2></div><div><p>Cada pessoa tem uma história, um tempo e uma beleza única. O primeiro passo é compreender o que faz sentido para você.</p><EssenzaButton outline to={essenzaPath('sobre')}>Conheça nossa essência</EssenzaButton></div><Leaf size={220} strokeWidth={.35} aria-hidden="true" /></div></section>
    <section className="en-section"><div className="en-container en-journey" data-reveal><div><span className="en-label">Como funciona</span><h2>Uma jornada<br /><em>pensada para você.</em></h2><p>Do primeiro contato ao acompanhamento, atenção em cada conversa.</p><Link className="en-link" to={essenzaPath('agendamento')}>Começar minha jornada<ArrowRight size={17} /></Link></div><ol>{[['Conversamos', 'Conhecemos suas expectativas e prioridades.'], ['Avaliamos', 'Uma conversa individual com o profissional.'], ['Planejamos', 'Possibilidades discutidas com clareza.'], ['Acompanhamos', 'Uma proposta de cuidado que valoriza o vínculo.']].map(([title, text], i) => <li key={title}><span>0{i + 1}</span><div><h3>{title}</h3><p>{text}</p></div></li>)}</ol><BeautyPhoto image="evaluation" alt="Avaliação facial ilustrativa em um ambiente reservado" /></div></section>
    <section className="en-section en-section--cream"><div className="en-container en-team-home" data-reveal><div><span className="en-label">Pessoas que cuidam</span><h2>Técnica, presença<br /><em>e um olhar humano.</em></h2><p>Conheça os profissionais que representam a experiência Essenza. Uma proposta de cuidado com escuta e atenção.</p><EssenzaButton outline to={essenzaPath('profissionais')}>Conheça nossa equipe</EssenzaButton><p className="bi-note">Perfis e trajetórias demonstrativos.</p></div><BeautyPhoto image="professional1" alt="Retrato ilustrativo de profissional de estética" /><BeautyPhoto image="teamCandid" alt="Equipe em uma conversa ilustrativa" /></div></section>
    <section className="en-section"><div className="en-container" data-reveal><EssenzaTitle label="Nossa estrutura" title={<>Um ambiente para<br /><em>se sentir bem.</em></>} to={essenzaPath('estrutura')} link="Explore a clínica" /><div className="en-spaces-home">{[{ image: 'reception', label: 'Uma chegada acolhedora' }, { image: 'room', label: 'Espaços reservados' }, { image: 'waiting', label: 'Conforto para estar presente' }].map(item => <Link key={item.image} to={essenzaPath('estrutura')}><BeautyPhoto image={item.image as 'reception' | 'room' | 'waiting'} alt={`${item.label} — ambiente ilustrativo`} /><span>{item.label}<ArrowRight size={17} /></span></Link>)}</div></div></section>
    <section className="en-section en-section--cream"><div className="en-container en-testimonial" data-reveal><BeautyPhoto image="patient" alt="Retrato ilustrativo de paciente" /><div aria-live="polite"><span className="en-label">Histórias de acolhimento</span><Quote size={38} strokeWidth={1} /><blockquote>“{stories[story][1]}”</blockquote><strong>{stories[story][0]}</strong><p className="bi-note">Relato fictício, criado para ilustrar a experiência.</p><div className="en-carousel-controls"><button aria-label="Depoimento anterior" onClick={() => setStory((story + stories.length - 1) % stories.length)}><ChevronLeft size={20} /></button><span>{story + 1} / {stories.length}</span><button aria-label="Próximo depoimento" onClick={() => setStory((story + 1) % stories.length)}><ChevronRight size={20} /></button></div></div></div></section>
    <section className="en-section"><div className="en-container en-wellness" data-reveal><div><span className="en-label">Uma pausa faz parte</span><h2>Bem-estar<br /><em>em cada detalhe.</em></h2><p>Texturas naturais, luz acolhedora e tempo para desacelerar. O cuidado também acontece no jeito de receber você.</p><EssenzaButton outline to={essenzaPath('tratamentos/ritual-wellness')}>Conheça o ritual wellness</EssenzaButton></div><BeautyPhoto image="detail" alt="Toalhas, aromas e elementos acolhedores em um ambiente de spa" /></div></section>
    <section className="en-section en-section--cream"><div className="en-container" data-reveal><EssenzaTitle label="Conteúdos Essenza" title={<>Um espaço para ler.<br /><em>E olhar para você.</em></>} to={essenzaPath('conteudos')} link="Todos os conteúdos" /><div className="en-articles">{beautyArticles.map(item => <article key={item.slug}><BeautyPhoto image={item.image} alt="Cena ilustrativa sobre autocuidado e bem-estar" /><span className="en-label">{item.category}</span><h3>{item.title}</h3><p>{item.text}</p><Link className="en-link" to={`${essenzaPath('conteudos')}?artigo=${item.slug}`}>Ler conteúdo<ArrowRight size={16} /></Link></article>)}</div></div></section>
    <section className="en-section"><div className="en-container en-booking-home" data-reveal><div><BeautyPhoto image="booking" alt="Agendamento ilustrativo pelo celular" /><div><span className="en-label">Seu primeiro encontro</span><h2>Um momento só seu.<br /><em>Vamos começar?</em></h2><p>O cuidado começa com uma conversa.</p></div></div><div><span className="en-label">Agende sua avaliação</span><h2>O primeiro passo<br />pode ser simples.</h2><p className="bi-note">Experimente a solicitação demonstrativa.</p><BeautyBookingForm homePath={essenzaPath()} /></div></div></section>
  </EssenzaLayout>
}
