import { Link } from 'react-router-dom';
import { NutritionBooking, NutritionFAQ, NutritionPhoto } from '../shared/NutritionUI';
import { nutritionPath } from '../shared/nutrition-images';
import { nutritionFaq } from '../shared/nutrition-types';
import { content } from './data/content';
import { ModelLink, NutritionLayout } from './NutritionLayout';
import { DigitalPanel } from '../shared/NutritionPanels';
export default function NutricionistaModel08Page() {
    return <NutritionLayout>
 <section className="ns-hero"><div className="ni-wrap ns-hero-grid"><div><span className="ni-eyebrow">Nutrição conectada / Cuidado humano</span><h1>Sua nutrição<br />conectada à sua<br /><em>evolução.</em></h1><p>Uma jornada organizada para conversar, planejar e acompanhar. Perto de você, onde você estiver.</p><div className="ni-actions"><ModelLink page="agendamento?modalidade=Online">Conheça a consulta online</ModelLink><ModelLink page="como-funciona" outline>Explore a jornada</ModelLink></div><div className="ns-status"><i />INTERFACE DEMONSTRATIVA / SEM CONEXÃO REAL</div></div><div className="ns-hero-media"><NutritionPhoto image={content.hero} alt="Consulta online ilustrativa em ambiente acolhedor" eager/><DigitalPanel compact/></div></div></section>
 <div className="ni-wrap ni-strip"><span>Escuta e atenção individual</span><span>Jornada digital demonstrativa</span><span>Planejamento conversado</span><span>Respeito à sua história</span></div>
 <section className="ni-section model-services"><div className="ni-wrap"><div className="ni-heading"><div><span className="ni-eyebrow">Áreas de atendimento</span><h2>Seu próximo cuidado. Conectado à sua rotina.</h2></div><ModelLink page="atendimentos" outline>Explore os recursos</ModelLink></div><div className="ni-services">{content.services.map((item, index) => <Link className="ni-service" key={item.slug} to={nutritionPath(content.model, 'atendimentos/' + item.slug)}><NutritionPhoto image={item.image} alt={item.name + ' — fotografia ilustrativa'}/><div><span className="ni-eyebrow">0{index + 1} / {item.category}</span><h3>{item.name}</h3><p>{item.text}</p><span className="ni-text-link">Conhecer →</span></div></Link>)}</div></div></section>
 <section className="ni-section"><div className="ni-wrap ns-journey"><div><span className="ni-eyebrow">01 / Connected journey</span><h2>O cuidado tem<br /><em>um caminho.</em></h2><p>A tecnologia organiza. A conversa aproxima. Explore as etapas de uma jornada demonstrativa.</p><ModelLink page="como-funciona" outline>Conhecer o fluxo</ModelLink></div><DigitalPanel /></div></section><section className="ni-section ns-surface"><div className="ni-wrap ns-call" data-reveal><NutritionPhoto image={content.consultation} alt="Cena ilustrativa de consulta nutricional por videochamada"/><div><span className="ni-eyebrow">02 / Online, human</span><h2>À distância.<br /><em>Com presença.</em></h2><p>{content.about}</p><ModelLink page="agendamento?modalidade=Online">Simular consulta online</ModelLink></div></div></section><section className="ni-section"><div className="ni-wrap"><span className="ni-eyebrow">03 / Da primeira conversa ao acompanhamento</span><h2>Um percurso.<br /><em>Do seu jeito.</em></h2><ol className="ni-journey">{content.journey.map((title, index) => <li key={title}><span>0{index + 1}</span><h3>{title}</h3><p>Organização e clareza em uma etapa discutida com você.</p></li>)}</ol></div></section><section className="ni-section ns-surface"><div className="ni-wrap ns-professional"><div><span className="ni-eyebrow">04 / Um olhar humano</span><h2>Por trás de um plano.<br /><em>Uma boa conversa.</em></h2><p>Um perfil ilustrativo da proposta NutriSync. Nome, CRN e formação a configurar.</p><ModelLink page="sobre" outline>Conheça a abordagem</ModelLink></div><NutritionPhoto image={content.profile} alt="Retrato ilustrativo de profissional organizando refeições"/></div></section>
 <section className="ni-section model-journal"><div className="ni-wrap"><div className="ni-heading"><div><span className="ni-eyebrow">Leituras para o seu momento</span><h2>Um espaço para refletir.</h2></div><ModelLink page="conteudos" outline>Todas as leituras</ModelLink></div><div className="ni-journal">{content.articles.slice(0, 2).map(article => <article key={article.slug}><Link to={nutritionPath(content.model, 'conteudos/' + article.slug)}><NutritionPhoto image={article.image} alt={article.title}/><span className="ni-eyebrow">{article.category}</span><h3>{article.title}</h3><p>{article.text}</p><span className="ni-text-link">Ler conteúdo →</span></Link></article>)}</div></div></section>
 <section className="ni-section model-faq"><div className="ni-wrap ni-split"><div><span className="ni-eyebrow">Antes de começar</span><h2>Uma conversa também tira dúvidas.</h2><p>Conheça a proposta de atendimento e como explorar esta experiência.</p><ModelLink page="como-funciona" outline>Como funciona</ModelLink></div><div>{nutritionFaq.map(item => <NutritionFAQ key={item.question} {...item}/>)}</div></div></section>
 <section className="ni-section model-booking"><div className="ni-wrap ni-booking-grid"><div><span className="ni-eyebrow">Seu próximo encontro</span><h2>Seu próximo passo começa aqui.</h2><p>Uma solicitação demonstrativa para experimentar o agendamento. Sem envio de dados ou reserva.</p><p className="ni-note">Use apenas dados fictícios e preferências de contato.</p></div><NutritionBooking model={content.model} services={content.services}/></div></section>
 <section className="ni-section model-contact"><div className="ni-wrap ni-split"><NutritionPhoto image={content.room} alt="Ambiente ilustrativo de consultório de nutrição"/><div><span className="ni-eyebrow">Online e presencial / Modalidades demonstrativas</span><h2>O cuidado começa na chegada.</h2><p>Endereço, horários e canais de atendimento a configurar.</p><ModelLink page="contato" outline>Conheça o contato</ModelLink></div></div></section>
 <section className="ni-closing"><div className="ni-wrap"><span className="ni-eyebrow">Uma conversa. Um próximo cuidado.</span><h2>{content.tagline}</h2><ModelLink /></div></section>
 </NutritionLayout>;
}
