import { Link } from 'react-router-dom'
import { BeautyAccordion, BeautyBookingForm, BeautyPhoto } from '../shared/BeautyInteractions'
import { beautyFaq, beautyTreatments } from '../shared/beauty-data'
import { SkinPanel, TreatmentTile } from '../shared/BeautyTools'
import { AuraLayout, AuraLink } from './AuraLayout'

export default function EsteticaBelezaModel03Page() {
  return <AuraLayout><section className="aura-hero"><div className="aura-wrap aura-hero-grid"><div><span className="bt-eyebrow">Skincare com propósito</span><h1>Entenda sua pele.<br /><em>Revele sua<br />melhor versão.</em></h1><p>Um olhar atento à sua história. Uma conversa para descobrir o que faz sentido para você.</p><AuraLink page="analise-da-pele">Conheça a análise da pele</AuraLink><span className="aura-hero-note">Beleza pessoal · Escuta · Cuidado</span></div><div className="aura-portrait"><BeautyPhoto image="skin" alt="Close-up ilustrativo de pele com luz natural" eager /><span>SKIN IS PERSONAL.</span></div></div></section>
    <section className="aura-section"><div className="aura-wrap aura-analysis" data-reveal><div><span className="bt-eyebrow">01 / Skin understanding</span><h2>Sua pele tem<br /><em>uma história.</em></h2><p>Antes de escolher, observar. Antes de indicar, ouvir. Conheça a experiência de uma avaliação individual.</p><AuraLink page="analise-da-pele">Um olhar mais próximo</AuraLink><BeautyPhoto image="evaluation" alt="Cena ilustrativa de análise facial em clínica" /></div><SkinPanel /></div></section>
    <section className="aura-section aura-nude"><div className="aura-wrap" data-reveal><span className="bt-eyebrow">02 / Suas prioridades</span><h2>O cuidado começa<br /><em>pelo que importa para você.</em></h2><div className="aura-objectives">{['Textura', 'Rotina', 'Autocuidado', 'Uma primeira conversa'].map((item, index) => <Link key={item} to="/estetica-beleza/modelo-03/objetivos"><span>0{index + 1}</span><h3>{item}</h3><span>Explore seu ponto de partida ↗</span></Link>)}</div></div></section>
    <section className="aura-section"><div className="aura-wrap"><span className="bt-eyebrow">03 / Protocolos</span><h2>Possibilidades de cuidado.<br /><em>Escolhas individuais.</em></h2><div className="aura-catalog">{[beautyTreatments[1], beautyTreatments[0], beautyTreatments[3]].map((item, index) => <TreatmentTile key={item.slug} item={item} index={index} model="03" />)}</div><AuraLink page="protocolos">Explore os protocolos</AuraLink></div></section>
    <section className="aura-section aura-wine"><div className="aura-wrap aura-split" data-reveal><BeautyPhoto image="technology" alt="Recurso tecnológico ilustrativo de estética" /><div><span className="bt-eyebrow">Tecnologia e presença</span><h2>Um recurso a mais.<br /><em>Um olhar que é seu.</em></h2><p>Recursos contemporâneos apoiam uma conversa. A avaliação profissional continua no centro de cada decisão.</p><AuraLink page="analise-da-pele">Entenda o processo</AuraLink></div></div></section>
    <section className="aura-section"><div className="aura-wrap aura-skincare" data-reveal><div><span className="bt-eyebrow">04 / No seu ritmo</span><h2>Uma rotina que<br /><em>tenha a sua medida.</em></h2><p>Tempo, presença e escolhas conscientes. Um espaço para conversar sobre o cuidado no seu dia a dia.</p><AuraLink page="skincare">Explore o skincare</AuraLink></div><BeautyPhoto image="content" alt="Autocuidado em uma rotina ilustrativa" /></div></section>
    <section className="aura-section aura-nude"><div className="aura-wrap aura-split"><BeautyPhoto image="professional1" alt="Retrato ilustrativo da especialista Aura Skin" /><div><span className="bt-eyebrow">05 / Sua especialista</span><h2>Uma conversa.<br /><em>Um cuidado próximo.</em></h2><p>Atenção à individualidade, escuta e clareza representam a proposta da Aura Skin.</p><AuraLink page="especialista">Conheça o olhar</AuraLink><p className="bi-note">Perfil e registro profissional fictícios.</p></div></div></section>
    <section className="aura-section"><div className="aura-wrap aura-split"><div><span className="bt-eyebrow">Antes de começar</span><h2>Suas dúvidas<br /><em>têm espaço aqui.</em></h2><AuraLink page="conteudos">Leituras sobre cuidado</AuraLink></div><div>{beautyFaq.slice(0, 4).map(item => <BeautyAccordion key={item.question} {...item} />)}</div></div></section>
    <section className="aura-section aura-nude"><div className="aura-wrap aura-book"><div><span className="bt-eyebrow">Vamos conversar?</span><h2>O primeiro passo<br /><em>é conhecer você.</em></h2><BeautyPhoto image="booking" alt="Cena ilustrativa de agendamento pelo celular" /></div><BeautyBookingForm homePath="/estetica-beleza/modelo-03" /></div></section>
  </AuraLayout>
}
