import { Link } from 'react-router-dom';
import { NutritionBooking, NutritionFAQ, NutritionPhoto } from '../shared/NutritionUI';
import { nutritionPath } from '../shared/nutrition-images';
import { nutritionFaq } from '../shared/nutrition-types';
import { content } from './data/content';
import { ModelLink, NutritionLayout } from './NutritionLayout';
export default function NutricionistaModel07Page() {
    return <NutritionLayout>
 <section className="rn-hero"><div className="ni-wrap rn-hero-grid"><div><span className="ni-eyebrow">Nutrição que acolhe a família</span><h1>Cuidando de<br /><em>cada fase</em><br />da vida.</h1><p>Histórias diferentes, necessidades próprias e uma mesa que acolhe. Um cuidado construído com a sua família.</p><div className="ni-actions"><ModelLink /><ModelLink page="atendimentos" outline>Encontre a sua fase</ModelLink></div></div><div className="rn-family"><NutritionPhoto image={content.hero} alt="Família à mesa em uma refeição ilustrativa" eager/><span>Juntos,<br />no ritmo de vocês.</span></div></div></section>
 <div className="ni-wrap ni-strip"><span>Escuta e atenção individual</span><span>Online e presencial</span><span>Planejamento conversado</span><span>Respeito à sua história</span></div>
 <section className="ni-section model-services"><div className="ni-wrap"><div className="ni-heading"><div><span className="ni-eyebrow">Áreas de atendimento</span><h2>Cada fase merece atenção.</h2></div><ModelLink page="atendimentos" outline>Encontre sua fase</ModelLink></div><div className="ni-services">{content.services.map((item, index) => <Link className="ni-service" key={item.slug} to={nutritionPath(content.model, 'atendimentos/' + item.slug)}><NutritionPhoto image={item.image} alt={item.name + ' — fotografia ilustrativa'}/><div><span className="ni-eyebrow">0{index + 1} / {item.category}</span><h3>{item.name}</h3><p>{item.text}</p><span className="ni-text-link">Conhecer →</span></div></Link>)}</div></div></section>
 <section className="ni-section rn-peach"><div className="ni-wrap rn-together"><div><span className="ni-eyebrow">Na sua fase, com você</span><h2>Cada família.<br /><em>Um jeito de cuidar.</em></h2><p>{content.about}</p><ModelLink page="como-funciona" outline>Conheça a jornada</ModelLink></div><NutritionPhoto image={content.food} alt="Cena ilustrativa de alimentação infantil à mesa"/></div></section><section className="ni-section"><div className="ni-wrap rn-kitchen" data-reveal><NutritionPhoto image={content.lifestyle} alt="Família cozinhando junta em cena ilustrativa"/><div><span className="ni-eyebrow">Encontros que fazem parte da vida</span><h2>Rotinas possíveis.<br /><em>Histórias compartilhadas.</em></h2><p>O acompanhamento considera o contexto da família e abre espaço para dúvidas de responsáveis e cuidadores.</p><ModelLink page="atendimentos">Explore as áreas</ModelLink></div></div></section><section className="ni-section rn-mint"><div className="ni-wrap"><span className="ni-eyebrow">Um cuidado que cresce junto</span><h2>Passo a passo.<br /><em>Com a sua família.</em></h2><ol className="ni-journey">{content.journey.map((title, index) => <li key={title}><span>0{index + 1}</span><h3>{title}</h3><p>Uma etapa individual, com atenção ao momento de cada família.</p></li>)}</ol><ModelLink page="como-funciona" outline>Entenda cada encontro</ModelLink></div></section><section className="ni-section"><div className="ni-wrap rn-professional"><div><span className="ni-eyebrow">Um olhar próximo</span><h2>Acolher é<br /><em>o nosso começo.</em></h2><p>Conheça a proposta de cuidado Raízes. Nome do profissional, formação e CRN a configurar.</p><ModelLink page="sobre">Conheça a abordagem</ModelLink></div><NutritionPhoto image={content.profile} alt="Retrato ilustrativo de profissional de nutrição"/></div></section>
 <section className="ni-section model-journal"><div className="ni-wrap"><div className="ni-heading"><div><span className="ni-eyebrow">Leituras para o seu momento</span><h2>Histórias, encontros e cuidado.</h2></div><ModelLink page="conteudos" outline>Todas as leituras</ModelLink></div><div className="ni-journal">{content.articles.slice(0, 2).map(article => <article key={article.slug}><Link to={nutritionPath(content.model, 'conteudos/' + article.slug)}><NutritionPhoto image={article.image} alt={article.title}/><span className="ni-eyebrow">{article.category}</span><h3>{article.title}</h3><p>{article.text}</p><span className="ni-text-link">Ler conteúdo →</span></Link></article>)}</div></div></section>
 <section className="ni-section model-faq"><div className="ni-wrap ni-split"><div><span className="ni-eyebrow">Antes de começar</span><h2>Uma conversa também tira dúvidas.</h2><p>Conheça a proposta de atendimento e como explorar esta experiência.</p><ModelLink page="como-funciona" outline>Como funciona</ModelLink></div><div>{nutritionFaq.map(item => <NutritionFAQ key={item.question} {...item}/>)}</div></div></section>
 <section className="ni-section model-booking"><div className="ni-wrap ni-booking-grid"><div><span className="ni-eyebrow">Seu próximo encontro</span><h2>Vamos conhecer a sua família?</h2><p>Uma solicitação demonstrativa para experimentar o agendamento. Sem envio de dados ou reserva.</p><p className="ni-note">Use apenas dados fictícios e preferências de contato.</p></div><NutritionBooking model={content.model} services={content.services}/></div></section>
 <section className="ni-section model-contact"><div className="ni-wrap ni-split"><NutritionPhoto image={content.room} alt="Ambiente ilustrativo de consultório de nutrição"/><div><span className="ni-eyebrow">Online e presencial / Modalidades demonstrativas</span><h2>O cuidado começa na chegada.</h2><p>Endereço, horários e canais de atendimento a configurar.</p><ModelLink page="contato" outline>Conheça o contato</ModelLink></div></div></section>
 <section className="ni-closing"><div className="ni-wrap"><span className="ni-eyebrow">Uma conversa. Um próximo cuidado.</span><h2>{content.tagline}</h2><ModelLink /></div></section>
 </NutritionLayout>;
}
