import { Link, useNavigate } from 'react-router-dom'
import { Search } from 'lucide-react'
import { BeautyAccordion, BeautyBookingForm, BeautyPhoto } from '../shared/BeautyInteractions'
import { beautyFaq, beautyTreatments } from '../shared/beauty-data'
import { TreatmentTile } from '../shared/BeautyTools'
import { ClinicLayout, ClinicLink } from './ClinicLayout'
export default function EsteticaBelezaModel07Page() {
  const navigate = useNavigate()
  return <ClinicLayout><section className="clinic-hero"><div className="clinic-wrap clinic-hero-grid"><div><span className="bt-eyebrow">Todas as áreas. Uma mesma atenção.</span><h1>Toda a estética.<br /><em>Um cuidado<br />integrado.</em></h1><p>Encontre seu ponto de partida. Tratamentos, profissionais e recursos em uma experiência feita para conversar com você.</p><form onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); navigate(`/estetica-beleza/modelo-07/busca?q=${encodeURIComponent(String(data.get('q') || ''))}`) }} className="clinic-home-search"><label><Search size={20} /><input name="q" type="search" aria-label="Buscar tratamento no catálogo" placeholder="Que cuidado você procura?" /></label><button type="submit">Buscar →</button></form><div className="clinic-quick">{['Facial', 'Pele', 'Corporal', 'Tecnologia'].map(category => <Link key={category} to={`/estetica-beleza/modelo-07/busca?categoria=${category}`}>{category}</Link>)}</div></div><BeautyPhoto image="team" alt="Equipe ilustrativa da Clínica 360 Beauty" eager /></div></section>
    <section className="clinic-section"><div className="clinic-wrap"><div className="clinic-heading"><div><span className="bt-eyebrow">Explore o catálogo</span><h2>Um próximo cuidado.<br /><em>Do seu jeito.</em></h2></div><ClinicLink page="tratamentos">Todos os tratamentos</ClinicLink></div><div className="clinic-catalog">{[beautyTreatments[0], beautyTreatments[1], beautyTreatments[2], beautyTreatments[3]].map((item, index) => <TreatmentTile key={item.slug} item={item} index={index} model="07" />)}</div></div></section>
    <section className="clinic-section clinic-mint"><div className="clinic-wrap"><span className="bt-eyebrow">Encontre por objetivo</span><h2>Por onde você<br /><em>quer começar?</em></h2><div className="clinic-objectives">{[['Pele', 'Minha rotina'], ['Facial', 'Meu rosto'], ['Corporal', 'Meu corpo'], ['Bem-estar', 'Meu momento']].map(([category, title]) => <Link key={title} to={`/estetica-beleza/modelo-07/busca?categoria=${encodeURIComponent(category)}`}><h3>{title}</h3><span>{category} →</span></Link>)}</div></div></section>
    <section className="clinic-section"><div className="clinic-wrap clinic-team" data-reveal><BeautyPhoto image="teamCandid" alt="Equipe ilustrativa conversando em clínica" /><div><span className="bt-eyebrow">Diferentes olhares</span><h2>Um time próximo.<br /><em>Um cuidado pessoal.</em></h2><p>Perfis ilustrativos que representam uma proposta de escuta, integração e atenção individual.</p><ClinicLink page="profissionais">Conheça a equipe</ClinicLink></div></div></section>
    <section className="clinic-section clinic-petrol"><div className="clinic-wrap clinic-technology"><div><span className="bt-eyebrow">Estrutura contemporânea</span><h2>Tecnologia com<br /><em>um propósito.</em></h2><p>Recursos que apoiam um planejamento discutido com cada pessoa, sem indicação automática.</p><ClinicLink page="tecnologias">Conheça os recursos</ClinicLink></div><BeautyPhoto image="equipment" alt="Equipamentos em clínica ilustrativa" /></div></section>
    <section className="clinic-section"><div className="clinic-wrap"><div className="clinic-heading"><h2>Um lugar para<br /><em>cuidar de você.</em></h2><ClinicLink page="estrutura">Visite a clínica</ClinicLink></div><div className="clinic-spaces">{[{ image: 'reception' as const, title: 'Recepção' }, { image: 'room' as const, title: 'Espaço reservado' }, { image: 'waiting' as const, title: 'Sala de espera' }].map(item => <Link key={item.image} to="/estetica-beleza/modelo-07/estrutura"><BeautyPhoto image={item.image} alt={`${item.title} ilustrativa`} /><span>{item.title} ↗</span></Link>)}</div></div></section>
    <section className="clinic-section clinic-mint"><div className="clinic-wrap clinic-book"><div><span className="bt-eyebrow">Comece com uma conversa</span><h2>O próximo cuidado<br /><em>começa aqui.</em></h2><p>Solicitação demonstrativa, sem reserva real ou envio de dados.</p>{beautyFaq.slice(0, 3).map(item => <BeautyAccordion key={item.question} {...item} />)}<ClinicLink page="conteudos">Leia mais sobre cuidado</ClinicLink></div><BeautyBookingForm homePath="/estetica-beleza/modelo-07" /></div></section>
  </ClinicLayout>
}
