import { useState } from 'react'
import { Link } from 'react-router-dom'
import { ArrowRight, ChevronLeft, ChevronRight, Quote, Star } from 'lucide-react'
import { articles, doctors, faqItems, primePath } from './prime-data'
import { PrimeAccordion, PrimeBenefits, PrimeButton, PrimeCTA, PrimeDoctorCards, PrimeHero, PrimeLayout, PrimeLocation, PrimePhoto, PrimeSectionTitle, PrimeSpecialtyCards } from './PrimeLayout'

const stories = [
  { name: 'Marina S.', photo: 'patient-01', quote: 'Uma experiência em que cada detalhe transmite acolhimento. Ter espaço para conversar fez toda a diferença.' },
  { name: 'Ricardo A.', photo: 'patient-02', quote: 'Gostei da atenção, do ambiente tranquilo e da clareza em cada etapa. O cuidado começa antes da consulta.' },
  { name: 'Ana C.', photo: 'patient-03', quote: 'Encontrar uma equipe que escuta com calma muda a forma como a gente vive o atendimento.' },
]
export default function MedicoModel02Page() {
  const [story, setStory] = useState(0)
  return <PrimeLayout>
    <PrimeHero home eyebrow="Essencial Prime · Medicina Particular" image="clinic-reception-02" title={<>Um novo padrão<br />de cuidado.<br /><em>Para você.</em></>} text="Medicina particular com tempo, presença e atenção a cada detalhe. Uma experiência feita para você e sua família."><PrimeButton /><PrimeButton secondary to={primePath('experiencia')}>Conheça a experiência</PrimeButton></PrimeHero>
    <PrimeBenefits />
    <section className="ep-section"><div className="ep-container ep-story" data-reveal><div className="ep-story__photos"><PrimePhoto name="doctor-consultation" alt="Conversa atenta entre médica e paciente" /><div className="ep-photo-caption"><span>O cuidado começa</span><strong>na escuta.</strong></div></div><div><span className="ep-eyebrow">A experiência Essencial Prime</span><h2>Mais que uma consulta.<br /><em>Um encontro com você.</em></h2><p>Uma história merece ser ouvida com calma. Um cuidado merece olhar para a pessoa inteira.</p><p>Reunimos uma equipe próxima e ambientes acolhedores para uma medicina particular que respeita seu tempo, sua privacidade e o seu momento de vida.</p><div className="ep-mini-pillars"><div><strong>01</strong><span>Escuta de verdade</span></div><div><strong>02</strong><span>Atenção individual</span></div><div><strong>03</strong><span>Cuidado contínuo</span></div></div><PrimeButton secondary to={primePath('experiencia')}>Descubra a Experiência Prime</PrimeButton></div></div></section>
    <section className="ep-section ep-section--ivory"><div className="ep-container" data-reveal><PrimeSectionTitle eyebrow="Especialidades" title={<>Um olhar completo.<br /><em>Em cada fase da vida.</em></>} text="Diferentes especialidades, uma mesma forma de cuidar." link="Todas as especialidades" to={primePath('especialidades')} /><PrimeSpecialtyCards /></div></section>
    <section className="ep-section"><div className="ep-container" data-reveal><PrimeSectionTitle eyebrow="Pessoas que cuidam de pessoas" title={<>Competência que acolhe.<br /><em>Presença que aproxima.</em></>} link="Conheça a equipe" to={primePath('equipe')} /><PrimeDoctorCards items={doctors.slice(0, 4)} /><p className="ep-note ep-center">Profissionais, registros e perfis demonstrativos. Fotografias ilustrativas.</p></div></section>
    <section className="ep-section ep-section--navy"><div className="ep-container" data-reveal><PrimeSectionTitle eyebrow="A sua jornada" title={<>Tudo começa com uma conversa.<br /><em>E continua com cuidado.</em></>} /><div className="ep-journey">{[['Seu primeiro contato', 'Escolha a especialidade e conheça quem vai acolher você.'], ['Um encontro com tempo', 'Um espaço reservado para compartilhar sua história.'], ['Decisões compartilhadas', 'Clareza para conversar sobre os próximos passos.'], ['Seguimos por perto', 'Uma proposta de acompanhamento, com atenção individual.']].map(([title, text], i) => <article key={title}><span>0{i + 1}</span><h3>{title}</h3><p>{text}</p></article>)}</div><div className="ep-numbers"><div><strong>06</strong><span>especialidades em conexão</span></div><div><strong>01</strong><span>experiência centrada em você</span></div><div><strong>05</strong><span>passos para simular seu agendamento</span></div><div><strong>100%</strong><span>atenção à experiência particular</span></div></div></div></section>
    <section className="ep-section"><div className="ep-container ep-story ep-story--reverse" data-reveal><div><span className="ep-eyebrow">Seu bem-estar em cada detalhe</span><h2>Um lugar para<br /><em>se sentir bem.</em></h2><p>Luz natural, materiais acolhedores e espaços reservados. Um ambiente pensado para deixar o cuidado acontecer com tranquilidade.</p><PrimeButton secondary to={primePath('estrutura')}>Conheça nossa estrutura</PrimeButton></div><div className="ep-facility-collage"><PrimePhoto name="clinic-corridor" alt="Corredor iluminado da clínica ilustrativa" /><PrimePhoto name="consultation-room" alt="Consultório particular ilustrativo" /><PrimePhoto name="clinic-detail" alt="Detalhes acolhedores do ambiente" /></div></div></section>
    <section className="ep-section ep-section--ivory"><div className="ep-container ep-testimonials" data-reveal><div><span className="ep-eyebrow">Histórias de acolhimento</span><h2>O cuidado também<br /><em>se sente.</em></h2><p className="ep-note">Relatos fictícios que ilustram a experiência proposta.</p><div className="ep-testimonial-controls"><button className="ep-icon-button" aria-label="Depoimento anterior" onClick={() => setStory((story + stories.length - 1) % stories.length)}><ChevronLeft /></button><span>{story + 1} / {stories.length}</span><button className="ep-icon-button" aria-label="Próximo depoimento" onClick={() => setStory((story + 1) % stories.length)}><ChevronRight /></button></div></div><div className="ep-testimonial" aria-live="polite"><Quote size={45} strokeWidth={1} /><div className="ep-stars" aria-label="Avaliação ilustrativa de cinco estrelas">{[1, 2, 3, 4, 5].map(n => <Star key={n} size={15} fill="currentColor" />)}</div><blockquote>{stories[story].quote}</blockquote><div className="ep-testimonial__person"><PrimePhoto name={stories[story].photo} alt="Retrato ilustrativo de paciente" /><div><strong>{stories[story].name}</strong><small>Depoimento demonstrativo</small></div></div></div></div></section>
    <section className="ep-section"><div className="ep-container" data-reveal><PrimeSectionTitle eyebrow="Conteúdos Prime" title={<>Informação com cuidado.<br /><em>Para o seu dia a dia.</em></>} link="Explore nossos conteúdos" to={primePath('conteudos')} /><div className="ep-editorial-grid">{articles.slice(0, 3).map(article => <article key={article.id}><PrimePhoto name={article.image} alt="Fotografia ilustrativa sobre cuidado e bem-estar" /><div><span className="ep-eyebrow">{article.category} · {article.time} de leitura</span><h3>{article.title}</h3><p>{article.text}</p><Link className="ep-text-link" to={primePath(article.id === 'habitos-vida-saudavel' ? 'conteudos/habitos-vida-saudavel' : 'conteudos')}>{article.id === 'habitos-vida-saudavel' ? 'Ler artigo' : 'Ver conteúdos'}<ArrowRight size={16} /></Link></div></article>)}</div></div></section>
    <PrimeCTA />
    <section className="ep-section"><div className="ep-container ep-faq-home" data-reveal><div><span className="ep-eyebrow">Podemos ajudar?</span><h2>Clareza desde<br /><em>o primeiro contato.</em></h2><Link className="ep-text-link" to={primePath('faq')}>Todas as dúvidas<ArrowRight size={17} /></Link></div><div>{faqItems.slice(0, 4).map(item => <PrimeAccordion key={item.question} {...item} />)}</div></div></section>
    <section className="ep-section ep-section--ivory"><div className="ep-container" data-reveal><PrimeLocation /></div></section>
  </PrimeLayout>
}
