import { useState } from 'react'
import { Link } from 'react-router-dom'
import { ArrowRight, CheckCircle2, Clock3, Heart, Mail, Maximize2, MessageCircle, Phone, Search, ShieldCheck, Users } from 'lucide-react'
import { articles, bookingPath, doctors, faqItems, normalizeSearch, primePath, specialties } from './prime-data'
import { PrimeAccordion, PrimeBenefits, PrimeButton, PrimeCheckList, PrimeCTA, PrimeDoctorCards, PrimeEmpty, PrimeHero, PrimeLayout, PrimeLocation, PrimeModal, PrimePhoto, PrimeSectionTitle, PrimeSpecialtyCards } from './PrimeLayout'

function SearchBox({ value, onChange, label }: { value: string; onChange: (value: string) => void; label: string }) {
  return <label className="ep-search"><input type="search" value={value} onChange={event => onChange(event.target.value)} placeholder={label} aria-label={label} /><Search size={18} aria-hidden="true" /></label>
}
function Filters({ items, active, onChange }: { items: string[]; active: string; onChange: (value: string) => void }) {
  return <div className="ep-filters" aria-label="Filtrar por categoria">{items.map(item => <button key={item} aria-pressed={active === item} onClick={() => onChange(item)}>{item}</button>)}</div>
}
function Pillars() {
  return <div className="ep-pillar-grid">{[{ Icon: Heart, title: 'Acolhimento', text: 'Começar por você, pela sua história e pelas suas expectativas.' }, { Icon: Clock3, title: 'Tempo e presença', text: 'Dar espaço às perguntas, às conversas e aos pequenos detalhes.' }, { Icon: ShieldCheck, title: 'Privacidade', text: 'Um ambiente reservado para viver o cuidado com tranquilidade.' }, { Icon: Users, title: 'Continuidade', text: 'Uma equipe que valoriza o vínculo e o acompanhamento.' }].map(({ Icon, title, text }) => <article key={title}><Icon size={32} strokeWidth={1.2} /><h3>{title}</h3><p>{text}</p></article>)}</div>
}
export function PrimeExperiencePage() {
  return <PrimeLayout><PrimeHero eyebrow="Experiência Prime" title={<>O cuidado vai além.<br /><em>A experiência também.</em></>} text="Uma medicina que respeita o seu tempo e entende que o acolhimento faz parte de cada encontro." image="patient-consultation" /><PrimeBenefits />
    <section className="ep-section"><div className="ep-container ep-story" data-reveal><div className="ep-story__photos"><PrimePhoto name="doctor-consultation" alt="Conversa próxima em um consultório ilustrativo" /><div className="ep-photo-caption"><span>Uma filosofia de cuidado</span><strong>Você no centro.</strong></div></div><div><span className="ep-eyebrow">Nossa filosofia</span><h2>Não é só sobre saúde.<br /><em>É sobre a sua história.</em></h2><p>Cada pessoa chega com um universo próprio. Na Essencial Prime, o cuidado começa com respeito a essa individualidade.</p><p>Da primeira conversa ao acompanhamento, a proposta é conectar atenção médica, comunicação clara e um ambiente que acolhe.</p><PrimeCheckList items={['Escuta atenta e decisões compartilhadas', 'Atendimento particular e reservado', 'Uma experiência pensada para a sua família']} /></div></div></section>
    <section className="ep-section ep-section--ivory"><div className="ep-container" data-reveal><PrimeSectionTitle eyebrow="O que nos move" title={<>Quatro pilares.<br /><em>Uma mesma essência.</em></>} /><Pillars /></div></section>
    <section className="ep-section"><div className="ep-container ep-story ep-story--reverse" data-reveal><div><span className="ep-eyebrow">O cuidado encontra um lugar</span><h2>Conforto para chegar.<br /><em>Tranquilidade para ficar.</em></h2><p>Ambientes com luz natural, materiais acolhedores e atenção à privacidade. Os detalhes compõem uma experiência calma e pessoal.</p><PrimeButton secondary to={primePath('estrutura')}>Explore os ambientes</PrimeButton></div><PrimePhoto name="clinic-corridor" alt="Ambiente contemporâneo da clínica ilustrativa" className="ep-wide-photo" /></div></section>
    <section className="ep-section ep-section--navy"><div className="ep-container ep-manifesto" data-reveal><span className="ep-eyebrow">Manifesto Essencial Prime</span><h2>Há coisas que pedem tempo.<br /><em>Cuidar é uma delas.</em></h2><p>Acreditamos na presença. Na escuta. Na clareza. Em uma medicina que enxerga a pessoa antes de qualquer coisa. O essencial é fazer você se sentir acolhido, respeitado e acompanhado.</p></div></section>
    <section className="ep-section"><div className="ep-container ep-story" data-reveal><PrimePhoto name="family-care" alt="Família em uma conversa de cuidado" className="ep-wide-photo" /><div><span className="ep-eyebrow">Todas as fases, cada história</span><h2>Um cuidado que<br /><em>acompanha a família.</em></h2><p>Diferentes idades e necessidades, o mesmo compromisso com a escuta. Conheça as especialidades que fazem parte da nossa proposta.</p><PrimeButton secondary to={primePath('especialidades')}>Conhecer especialidades</PrimeButton></div></div></section><PrimeCTA /></PrimeLayout>
}
export function PrimeSpecialtiesPage() {
  const [query, setQuery] = useState('')
  const items = specialties.filter(item => normalizeSearch(`${item.name} ${item.description}`).includes(normalizeSearch(query)))
  return <PrimeLayout><PrimeHero eyebrow="Especialidades" title={<>Diferentes olhares.<br /><em>Um cuidado completo.</em></>} text="Especialidades que se conectam à sua história, com atenção individual em cada fase da vida." image="general-medicine" />
    <section className="ep-section"><div className="ep-container"><PrimeSectionTitle eyebrow="Encontre o seu cuidado" title="Nossas especialidades" /><div className="ep-toolbar"><SearchBox value={query} onChange={setQuery} label="Buscar uma especialidade" /><span className="ep-note" role="status">{items.length} especialidade{items.length !== 1 ? 's' : ''}</span></div>{items.length ? <PrimeSpecialtyCards items={items} /> : <PrimeEmpty reset={() => setQuery('')}>Experimente buscar pelo nome de uma especialidade.</PrimeEmpty>}</div></section>
    <section className="ep-section ep-section--navy"><div className="ep-container ep-story" data-reveal><PrimePhoto name="cardiology" alt="Consulta ilustrativa em cardiologia" className="ep-wide-photo" /><div><span className="ep-eyebrow">Um olhar para o seu coração</span><h2>Cardiologia com<br /><em>atenção à sua história.</em></h2><p>Uma conversa sobre acompanhamento, prevenção e prioridades individuais, com tempo para compreender os próximos passos.</p><PrimeButton to={primePath('especialidades/cardiologia')}>Conheça a cardiologia</PrimeButton></div></div></section><PrimeCTA /></PrimeLayout>
}
export function PrimeCardiologyPage() {
  return <PrimeLayout><PrimeHero eyebrow="Cardiologia" title={<>Um cuidado atento.<br /><em>De coração.</em></>} text="Uma especialidade que olha para você, sua história e o acompanhamento que faz sentido para o seu momento." image="cardiology"><PrimeButton to={bookingPath('cardiologia')} /><PrimeButton secondary to={primePath('equipe/helena-martins')}>Conheça a especialista</PrimeButton></PrimeHero><PrimeBenefits />
    <section className="ep-section"><div className="ep-container" data-reveal><PrimeSectionTitle eyebrow="O começo é uma conversa" title="Espaço para suas perguntas" text="Uma consulta permite conversar sobre seu contexto e organizar o acompanhamento com orientação individual." /><div className="ep-pillar-grid">{[['Histórico pessoal', 'Compartilhe as informações e avaliações anteriores que considera relevantes.'], ['Histórico familiar', 'Converse sobre a história da sua família e suas dúvidas.'], ['Acompanhamento', 'Revise com a especialista o que já faz parte do seu cuidado.'], ['Planejamento', 'Conheça os próximos passos definidos em uma avaliação individual.']].map(([title, text]) => <article key={title}><Heart size={28} strokeWidth={1.2} /><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section className="ep-section ep-section--ivory"><div className="ep-container ep-story" data-reveal><div><span className="ep-eyebrow">Clareza em cada etapa</span><h2>Acompanhamento.<br /><em>Com um olhar individual.</em></h2><p>Tratamentos e exames são discutidos após a avaliação clínica. Esta demonstração apresenta a experiência de atendimento e não define condutas ou indica exames.</p><PrimeCheckList items={['Conversa sobre prevenção e acompanhamento', 'Revisão de informações e exames anteriores', 'Discussão individual de exames, como ECG e ecocardiograma', 'Decisões e orientações compartilhadas']} /><PrimeButton to={bookingPath('cardiologia')}>Simular uma consulta</PrimeButton></div><PrimePhoto name="equipment-room" alt="Equipamentos em ambiente médico ilustrativo" className="ep-wide-photo" /></div></section>
    <section className="ep-section"><div className="ep-container ep-story" data-reveal><PrimePhoto name="doctor-profile" alt="Retrato ilustrativo de Helena Martins" className="ep-profile-photo" /><div><span className="ep-eyebrow">Sua especialista</span><h2>Dra. Helena Martins</h2><p>Uma proposta de cardiologia que valoriza o vínculo, a comunicação e o cuidado próximo.</p><p className="ep-note">CRM/SP 000000 · RQE 000000<br />Perfil e formação fictícios. Fotografia ilustrativa.</p><PrimeButton secondary to={primePath('equipe/helena-martins')}>Ver perfil completo</PrimeButton></div></div></section><PrimeCTA /></PrimeLayout>
}
export function PrimeTeamPage() {
  const [query, setQuery] = useState('')
  const [specialty, setSpecialty] = useState('')
  const items = doctors.filter(doctor => (!specialty || specialty === doctor.specialty) && normalizeSearch(`${doctor.name} ${specialties.find(item => item.id === doctor.specialty)?.name}`).includes(normalizeSearch(query)))
  return <PrimeLayout><PrimeHero eyebrow="Equipe médica" title={<>Pessoas que cuidam.<br /><em>Pessoas que escutam.</em></>} text="Conheça os profissionais que representam a proposta de atenção, presença e cuidado da Essencial Prime." image="team" /><PrimeBenefits />
    <section className="ep-section"><div className="ep-container"><PrimeSectionTitle eyebrow="Encontre seu profissional" title="Uma equipe próxima de você" /><div className="ep-toolbar"><SearchBox label="Buscar nome ou especialidade" value={query} onChange={setQuery} /><label className="ep-select-label">Especialidade<select aria-label="Filtrar equipe por especialidade" value={specialty} onChange={event => setSpecialty(event.target.value)}><option value="">Todas as especialidades</option>{specialties.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label></div><p className="ep-note" role="status">{items.length} profissional{items.length !== 1 ? 'is' : ''} encontrado{items.length !== 1 ? 's' : ''}</p>{items.length ? <PrimeDoctorCards items={items} /> : <PrimeEmpty reset={() => { setQuery(''); setSpecialty('') }}>Tente outro nome ou outra especialidade.</PrimeEmpty>}<p className="ep-note ep-center">Todos os nomes, registros e trajetórias são fictícios. Fotografias ilustrativas do banco compartilhado.</p></div></section><PrimeCTA /></PrimeLayout>
}
export function PrimeDoctorPage() {
  return <PrimeLayout><PrimeHero eyebrow="Equipe · Cardiologia" title={<>Dra. Helena<br /><em>Martins</em></>} text="Escuta, atenção individual e cuidado próximo em cada encontro. Perfil demonstrativo de cardiologia." image="doctor-profile" position="65% 30%"><PrimeButton to={bookingPath('cardiologia', 'helena-martins')} /><PrimeButton secondary to={primePath('especialidades/cardiologia')}>Conheça a cardiologia</PrimeButton></PrimeHero>
    <div className="ep-profile-nav ep-container"><a href="#ep-perfil">Sobre a médica</a><a href="#ep-formacao">Formação</a><a href="#ep-atuacao">Áreas de atuação</a><a href="#ep-avaliacoes">Avaliações</a></div>
    <section className="ep-section" id="ep-perfil"><div className="ep-container ep-story" data-reveal><div><span className="ep-eyebrow">Uma presença que acolhe</span><h2>Um olhar humano.<br /><em>Uma conversa com tempo.</em></h2><p>Este perfil representa uma profissional que valoriza conhecer a pessoa, ouvir suas perguntas e conversar sobre o acompanhamento com clareza.</p><blockquote className="ep-doctor-quote">“Cada história merece ser ouvida com atenção.”</blockquote><p className="ep-note">CRM/SP 000000 · RQE 000000<br />Nome, formação e trajetória inteiramente fictícios.</p></div><PrimePhoto name="doctor-consultation" alt="Médica e paciente em uma conversa ilustrativa" className="ep-wide-photo" /></div></section>
    <section className="ep-section ep-section--ivory" id="ep-formacao"><div className="ep-container" data-reveal><PrimeSectionTitle eyebrow="Trajetória demonstrativa" title="Formação e desenvolvimento" /><div className="ep-pillar-grid">{[['01', 'Graduação em Medicina'], ['02', 'Residência em Cardiologia'], ['03', 'Atenção ao acompanhamento'], ['04', 'Atualização profissional']].map(([number, title]) => <article key={number}><span className="ep-eyebrow">{number}</span><h3>{title}</h3><p>Etapa ilustrativa, sem vínculo com instituição real ou certificação profissional.</p></article>)}</div></div></section>
    <section className="ep-section" id="ep-atuacao"><div className="ep-container ep-story" data-reveal><div><span className="ep-eyebrow">Áreas de atuação</span><h2>Cuidado contínuo.<br /><em>Decisões compartilhadas.</em></h2><PrimeCheckList items={['Consulta particular em cardiologia', 'Conversa sobre prevenção e histórico familiar', 'Acompanhamento individual', 'Discussão de tratamentos e exames após avaliação']} /><PrimeButton to={bookingPath('cardiologia', 'helena-martins')}>Agendar com Helena</PrimeButton></div><PrimePhoto name="cardiology" alt="Cena ilustrativa de uma consulta de cardiologia" className="ep-wide-photo" /></div></section>
    <section className="ep-section ep-section--ivory" id="ep-avaliacoes"><div className="ep-container ep-manifesto" data-reveal><span className="ep-eyebrow">Uma experiência de acolhimento</span><h2>“Me senti ouvido.<br /><em>Do começo ao fim.”</em></h2><p>Relato fictício de paciente, criado para apresentar o componente de avaliação. Não representa uma avaliação clínica real.</p></div></section><PrimeCTA /></PrimeLayout>
}
const environments = [
  ['clinic-corridor', 'Uma chegada tranquila'], ['consultation-room', 'Consultórios reservados'], ['clinic-detail', 'Detalhes que acolhem'],
  ['equipment-room', 'Ambiente de exames'], ['clinic-facade', 'Acesso à unidade'], ['team-candid', 'Pessoas e presença'],
]
export function PrimeFacilitiesPage() {
  const [selected, setSelected] = useState<number | null>(null)
  return <PrimeLayout><PrimeHero eyebrow="Nossa estrutura" title={<>O cuidado está<br /><em>em cada detalhe.</em></>} text="Uma proposta de espaço contemporâneo, reservado e acolhedor. Conforto para você viver o seu momento com tranquilidade." image="clinic-corridor"><PrimeButton /><a className="ep-button ep-button--outline" href="#ep-ambientes">Explore os ambientes<ArrowRight size={17} /></a></PrimeHero><PrimeBenefits />
    <section className="ep-section" id="ep-ambientes"><div className="ep-container" data-reveal><PrimeSectionTitle eyebrow="Explore a unidade" title={<>Bem-vindo a um lugar<br /><em>pensado para você.</em></>} text="Selecione um ambiente para ampliar a fotografia. Imagens e instalações ilustrativas." /><div className="ep-gallery">{environments.map(([image, label], index) => <button key={image} onClick={() => setSelected(index)} aria-label={`Ampliar: ${label}`}><PrimePhoto name={image} alt={`${label} — fotografia ilustrativa`} /><span>{label}<Maximize2 size={16} /></span></button>)}</div></div></section>
    <section className="ep-section ep-section--ivory"><div className="ep-container" data-reveal><PrimeSectionTitle eyebrow="Conforto e acesso" title="A experiência começa na chegada" /><div className="ep-pillar-grid">{[['Acessibilidade', 'Uma proposta de circulação confortável e ambientes acessíveis.'], ['Privacidade', 'Consultórios reservados e atenção às conversas.'], ['Estacionamento', 'Facilidade de acesso como parte do projeto ilustrativo.'], ['Localização', 'Uma unidade demonstrativa na região da Avenida Paulista.']].map(([title, text]) => <article key={title}><ShieldCheck size={28} strokeWidth={1.2} /><h3>{title}</h3><p>{text}</p></article>)}</div><p className="ep-note">Condições de acesso e recursos devem ser confirmados ao adaptar o projeto para uma unidade real.</p></div></section>
    <section className="ep-section"><div className="ep-container" data-reveal><PrimeLocation /></div></section><PrimeCTA /><PrimeModal title={selected !== null ? environments[selected][1] : ''} open={selected !== null} onClose={() => setSelected(null)}>{selected !== null && <><PrimePhoto name={environments[selected][0]} alt={environments[selected][1]} /><div className="ep-actions"><button className="ep-button ep-button--outline" onClick={() => setSelected((selected + environments.length - 1) % environments.length)}>Anterior</button><button className="ep-button" onClick={() => setSelected((selected + 1) % environments.length)}>Próximo<ArrowRight size={16} /></button></div><p className="ep-note">Ambiente {selected + 1} de {environments.length} · Fotografias ilustrativas.</p></>}</PrimeModal></PrimeLayout>
}
export function PrimeContentsPage() {
  const [query, setQuery] = useState('')
  const [category, setCategory] = useState('Todos')
  const [selected, setSelected] = useState<(typeof articles)[number] | null>(null)
  const [subscribed, setSubscribed] = useState(false)
  const items = articles.filter(article => (category === 'Todos' || article.category === category) && normalizeSearch(`${article.title} ${article.text} ${article.category}`).includes(normalizeSearch(query)))
  return <PrimeLayout><PrimeHero eyebrow="Conteúdos Prime" title={<>Um espaço para ler.<br /><em>E olhar para você.</em></>} text="Conversas sobre cuidado, presença e escolhas do dia a dia. Conteúdo editorial demonstrativo, sem orientação médica individual." image="family-care"><PrimeButton secondary to={primePath('conteudos/habitos-vida-saudavel')}>Leia o destaque</PrimeButton></PrimeHero>
    <section className="ep-section"><div className="ep-container"><div className="ep-toolbar"><SearchBox label="Buscar artigos e temas" value={query} onChange={setQuery} /><Filters items={['Todos', 'Bem-estar', 'Cuidado', 'Família']} active={category} onChange={setCategory} /></div><PrimeSectionTitle eyebrow="Seleção editorial" title="Para uma leitura com calma" /><p className="ep-note" role="status">{items.length} conteúdo{items.length !== 1 ? 's' : ''} encontrado{items.length !== 1 ? 's' : ''}</p>{items.length ? <div className="ep-editorial-grid">{items.map(article => <article key={article.id}><PrimePhoto name={article.image} alt={`Fotografia ilustrativa de ${article.category}`} /><div><span className="ep-eyebrow">{article.category} · {article.time} de leitura</span><h3>{article.title}</h3><p>{article.text}</p>{article.id === 'habitos-vida-saudavel' ? <Link className="ep-text-link" to={primePath('conteudos/habitos-vida-saudavel')}>Ler artigo<ArrowRight size={16} /></Link> : <button className="ep-text-link" onClick={() => setSelected(article)}>Ler conteúdo<ArrowRight size={16} /></button>}</div></article>)}</div> : <PrimeEmpty reset={() => { setQuery(''); setCategory('Todos') }}>Busque outro tema ou escolha uma categoria diferente.</PrimeEmpty>}
    <div className="ep-newsletter"><div><span className="ep-eyebrow">Uma boa conversa, de vez em quando</span><h2>Cuidado também<br />em forma de leitura.</h2><p>Conheça a experiência de assinatura da nossa newsletter.</p></div>{subscribed ? <div className="ep-success" role="status"><CheckCircle2 /><strong>Assinatura simulada.</strong><p>Nenhum e-mail foi enviado ou armazenado.</p><button className="ep-button" onClick={() => setSubscribed(false)}>Testar novamente</button></div> : <form className="ep-form" onSubmit={event => { event.preventDefault(); event.currentTarget.reset(); setSubscribed(true) }}><label>Seu e-mail<input type="email" name="email" required placeholder="voce@exemplo.com" maxLength={180} /></label><label className="ep-consent"><input type="checkbox" required />Quero experimentar a assinatura demonstrativa, sem envio real de dados.</label><button className="ep-button" type="submit">Quero receber<ArrowRight size={17} /></button></form>}</div></div></section><PrimeCTA />
    <PrimeModal title={selected?.title || ''} open={selected !== null} onClose={() => setSelected(null)}>{selected && <><span className="ep-eyebrow">{selected.category} · Leitura demonstrativa</span><p>{selected.text}</p><p>Reserve um momento para pensar no que deseja compartilhar em sua próxima conversa. Anotar prioridades, dúvidas e informações pode ajudar a apresentar sua história com mais clareza.</p><p>O cuidado é uma experiência pessoal. A proposta deste espaço é abrir conversas e acolher diferentes momentos, sem substituir uma avaliação profissional.</p><PrimeButton to={primePath('conteudos/habitos-vida-saudavel')}>Explore o artigo em destaque</PrimeButton></>}</PrimeModal></PrimeLayout>
}
const articleSections = [
  ['rotina', 'Olhar para a própria rotina', 'Antes de mudar qualquer coisa, vale perceber como os dias acontecem. O que ocupa seu tempo? Quais momentos parecem importantes? Este é um convite à reflexão, sem uma fórmula igual para todo mundo.'],
  ['presenca', 'Reservar espaço para estar presente', 'Um encontro com a família, uma conversa sem pressa ou um momento silencioso podem ter significados diferentes para cada pessoa. Pense em quais experiências você gostaria de ter mais espaço para viver.'],
  ['escolhas', 'Fazer escolhas que cabem na sua vida', 'Quando uma intenção parece distante, olhar para o contexto ajuda a formular perguntas mais concretas. O que faz sentido agora? O que precisa de apoio? Há alguém com quem você gostaria de conversar?'],
  ['conversa', 'Levar suas perguntas para a consulta', 'Dúvidas, expectativas, informações de atendimentos anteriores e o que você considera importante na sua história são bons pontos de partida para uma conversa. Orientações de saúde dependem de avaliação individual.'],
  ['continuidade', 'Dar continuidade à conversa', 'O cuidado não se resume a um único encontro. A proposta da Essencial Prime é valorizar a escuta, a clareza e um acompanhamento combinado com cada pessoa. Nenhum plano ou tratamento é definido por este artigo.'],
]
export function PrimeArticlePage() {
  const [copied, setCopied] = useState('')
  async function share() {
    try { await navigator.clipboard.writeText(window.location.href); setCopied('Link copiado.') } catch { setCopied('Não foi possível copiar. Você pode compartilhar o endereço da barra do navegador.') }
  }
  return <PrimeLayout><PrimeHero eyebrow="Conteúdos · Bem-estar" title={<>Hábitos e uma vida<br /><em>com mais equilíbrio.</em></>} text="Tempo, presença e escolhas possíveis. Um convite editorial para olhar para a própria rotina." image="family-care"><span className="ep-reading-time"><Clock3 size={17} />5 min de leitura · Editorial demonstrativo</span></PrimeHero>
    <section className="ep-section"><div className="ep-container ep-article"><aside><h2>Neste artigo</h2><nav aria-label="Índice do artigo">{articleSections.map(([id, title], index) => <a key={id} href={`#ep-artigo-${id}`}>{index + 1}. {title}</a>)}</nav><PrimePhoto name="doctor-profile" alt="Retrato ilustrativo da revisora editorial" /><p>Revisão médica demonstrativa<br /><strong>Dra. Helena Martins</strong><br />CRM/SP 000000 · Perfil fictício</p><PrimeButton to={bookingPath('cardiologia', 'helena-martins')}>Agendar</PrimeButton></aside><article><p className="ep-note">Texto demonstrativo de bem-estar e experiência de cuidado. Não contém diagnóstico ou orientação médica individual.</p>{articleSections.map(([id, title, text], index) => <section key={id} id={`ep-artigo-${id}`}><h2>{index + 1}. {title}</h2><p>{text}</p>{index === 0 && <blockquote>O cuidado começa quando existe espaço para ouvir a sua história.</blockquote>}{index === 1 && <PrimePhoto name="family-care" alt="Conversa acolhedora com uma família" />}</section>)}<div className="ep-actions"><button className="ep-button ep-button--outline" onClick={share}>Copiar link<ArrowRight size={16} /></button><PrimeButton secondary to={primePath('conteudos')}>Mais conteúdos</PrimeButton></div><p className="ep-note" role="status">{copied}</p></article></div></section><PrimeCTA /></PrimeLayout>
}
export function PrimeContactPage() {
  const [sent, setSent] = useState(false)
  const [channel, setChannel] = useState<string | null>(null)
  return <PrimeLayout><PrimeHero eyebrow="Contato e localização" title={<>Estamos aqui.<br /><em>Para ouvir você.</em></>} text="O primeiro contato também faz parte do cuidado. Conheça a nossa experiência de concierge e localização." image="clinic-corridor" />
    <section className="ep-section"><div className="ep-container ep-contact-grid"><div><PrimeLocation /><div className="ep-contact-methods">{[{ Icon: Phone, label: 'Telefone', info: '(11) 0000-0000' }, { Icon: MessageCircle, label: 'WhatsApp', info: 'Concierge demonstrativo' }, { Icon: Mail, label: 'E-mail', info: 'contato@example.com' }].map(({ Icon, label, info }) => <button key={label} onClick={() => setChannel(label)}><Icon size={22} />{label}<small>{info}</small></button>)}</div></div><div className="ep-contact-panel"><span className="ep-eyebrow">Uma conversa começa aqui</span><h2>Envie uma mensagem</h2><p className="ep-note">Formulário demonstrativo. Use dados fictícios; não há envio real.</p>{sent ? <div className="ep-success" role="status"><CheckCircle2 /><h3>Mensagem simulada.</h3><p>Você concluiu a experiência. Nenhum dado foi enviado ou salvo.</p><button className="ep-button" onClick={() => setSent(false)}>Escrever outra mensagem</button></div> : <form className="ep-form" onSubmit={event => { event.preventDefault(); event.currentTarget.reset(); setSent(true) }}><label>Nome completo<input required name="name" minLength={3} maxLength={100} autoComplete="name" placeholder="Seu nome" /></label><div className="ep-form-row"><label>E-mail<input type="email" required name="email" maxLength={180} placeholder="voce@exemplo.com" autoComplete="email" /></label><label>Telefone<input type="tel" required name="phone" maxLength={20} pattern="[0-9+\(\) .\-]{10,20}" title="Informe um telefone com pelo menos 10 caracteres, usando números e separadores." placeholder="(11) 00000-0000" autoComplete="tel" /></label></div><label>Assunto<select required name="subject" defaultValue=""><option value="" disabled>Como podemos ajudar?</option><option>Agendamento</option><option>Experiência Prime</option><option>Estrutura e localização</option><option>Outra dúvida</option></select></label><label>Sua mensagem<textarea name="message" required minLength={10} maxLength={1500} placeholder="Compartilhe sua dúvida, sem dados de saúde." /></label><label className="ep-consent"><input type="checkbox" required />Entendo que esta é uma simulação, sem atendimento ou envio de dados.</label><button type="submit" className="ep-button">Simular envio<ArrowRight size={17} /></button></form>}</div></div></section>
    <section className="ep-section ep-section--ivory"><div className="ep-container" data-reveal><PrimeSectionTitle eyebrow="Antes do seu primeiro encontro" title="Podemos esclarecer suas dúvidas" link="Consultar perguntas frequentes" to={primePath('faq')} /><div className="ep-faq-home"><PrimeAccordion {...faqItems[0]} /><PrimeAccordion {...faqItems[4]} /></div></div></section><PrimeModal title={channel || ''} open={channel !== null} onClose={() => setChannel(null)}><p>Este canal é ilustrativo. A Essencial Prime não possui telefone, WhatsApp ou e-mail de atendimento real.</p><p>Ao adaptar o modelo para uma clínica, os contatos podem ser conectados aqui.</p><PrimeButton to={bookingPath()}>Conhecer o agendamento</PrimeButton></PrimeModal></PrimeLayout>
}
export function PrimeFAQPage() {
  const [query, setQuery] = useState('')
  const [category, setCategory] = useState('Todos')
  const categories = ['Todos', ...new Set(faqItems.map(item => item.category))]
  const items = faqItems.filter(item => (category === 'Todos' || category === item.category) && normalizeSearch(`${item.question} ${item.answer}`).includes(normalizeSearch(query)))
  return <PrimeLayout><PrimeHero eyebrow="Dúvidas frequentes" title={<>Clareza para começar.<br /><em>Tranquilidade para seguir.</em></>} text="Respostas sobre a experiência, o agendamento e os recursos desta demonstração." image="doctor-profile" />
    <section className="ep-section"><div className="ep-container"><div className="ep-toolbar"><SearchBox label="Buscar uma dúvida" value={query} onChange={setQuery} /><Filters items={categories} active={category} onChange={setCategory} /></div><p className="ep-note" role="status">{items.length} resposta{items.length !== 1 ? 's' : ''} encontrada{items.length !== 1 ? 's' : ''}</p><div className="ep-faq-layout"><div>{items.length ? categories.slice(1).map(group => { const grouped = items.filter(item => item.category === group); return grouped.length ? <section className="ep-faq-group" key={group}><h2>{group}</h2>{grouped.map(item => <PrimeAccordion key={item.question} {...item} />)}</section> : null }) : <PrimeEmpty reset={() => { setQuery(''); setCategory('Todos') }}>Tente outro termo ou consulte todas as categorias.</PrimeEmpty>}</div><aside className="ep-faq-concierge"><PrimePhoto name="team-candid" alt="Equipe ilustrativa em um ambiente acolhedor" /><div><span className="ep-eyebrow">Ainda tem dúvidas?</span><h3>Vamos conversar.</h3><p>Explore o contato e conheça a proposta de acolhimento da nossa equipe.</p><PrimeButton to={primePath('contato')}>Fale com o concierge</PrimeButton></div></aside></div></div></section><PrimeCTA /></PrimeLayout>
}


