import { Link } from 'react-router-dom';
import { NutritionBooking, NutritionFAQ, NutritionPhoto } from '../shared/NutritionUI';
import { nutritionPath } from '../shared/nutrition-images';
import { nutritionFaq } from '../shared/nutrition-types';
import { content } from './data/content';
import { ModelLink, NutritionLayout } from './NutritionLayout';
export default function NutricionistaModel03Page() {
    return <NutritionLayout>
 <section className="fp-hero"><div className="ni-wrap fp-hero-grid"><div><span className="ni-eyebrow">Nutrição esportiva. Rotina real.</span><h1>ALIMENTE<br />SUA<br /><em>EVOLUÇÃO.</em></h1><p>Seu esporte, sua rotina e suas prioridades. Um acompanhamento individual para cada etapa da sua jornada.</p><div className="ni-actions"><ModelLink /><ModelLink page="atendimentos" outline>Escolha seu ponto de partida</ModelLink></div></div><div className="fp-athlete"><NutritionPhoto image={content.hero} alt="Corrida em parque ao pôr do sol — cena ilustrativa" eager/><span>MOVE. FUEL. REPEAT.<br />NO SEU RITMO.</span></div></div></section>
 <div className="ni-wrap ni-strip"><span>SEU ESPORTE. SUA ROTINA.</span><span>Online e presencial</span><span>Planejamento conversado</span><span>Respeito à sua história</span></div>
 <section className="ni-section model-services"><div className="ni-wrap"><div className="ni-heading"><div><span className="ni-eyebrow">Áreas de atendimento</span><h2>DIFERENTES ESPORTES. UM CUIDADO INDIVIDUAL.</h2></div><ModelLink page="atendimentos" outline>Escolha seu ponto de partida</ModelLink></div><div className="ni-services">{content.services.map((item, index) => <Link className="ni-service" key={item.slug} to={nutritionPath(content.model, 'atendimentos/' + item.slug)}><NutritionPhoto image={item.image} alt={item.name + ' — fotografia ilustrativa'}/><div><span className="ni-eyebrow">0{index + 1} / {item.category}</span><h3>{item.name}</h3><p>{item.text}</p><span className="ni-text-link">Conhecer →</span></div></Link>)}</div></div></section>
 <section className="ni-section fp-method"><div className="ni-wrap"><span className="ni-eyebrow">01 / O seu planejamento</span><h2>ESTRATÉGIA.<br /><em>EM CADA ETAPA.</em></h2><ol className="ni-journey">{content.journey.map((title, index) => <li key={title}><span>0{index + 1}</span><h3>{title}</h3><p>Uma etapa discutida individualmente, considerando seu esporte e sua rotina.</p></li>)}</ol><ModelLink page="como-funciona" outline>Conheça o método</ModelLink></div></section><section className="ni-section"><div className="ni-wrap fp-fuel" data-reveal><NutritionPhoto image={content.food} alt="Refeição ilustrativa em bowl com alimentos variados"/><div><span className="ni-eyebrow">02 / Mais que um treino</span><h2>SUA ROTINA.<br />SEU ESPORTE.<br /><em>SEU CUIDADO.</em></h2><p>{content.about}</p><ModelLink page="atendimentos">Explore as áreas</ModelLink></div></div></section><section className="ni-section fp-surface"><div className="ni-wrap fp-professional"><div><span className="ni-eyebrow">03 / Um olhar profissional</span><h2>UM PLANO COMEÇA<br /><em>POR ESCUTAR.</em></h2><p>Conhecer sua rotina e suas expectativas é parte da proposta de avaliação.</p><ModelLink page="sobre" outline>Conheça a abordagem</ModelLink><p className="ni-note">Retrato ilustrativo. Nome e CRN a configurar.</p></div><NutritionPhoto image={content.profile} alt="Retrato ilustrativo de profissional de nutrição"/></div></section>
 <section className="ni-section model-journal"><div className="ni-wrap"><div className="ni-heading"><div><span className="ni-eyebrow">Leituras para o seu momento</span><h2>UMA PAUSA PARA ENTENDER.</h2></div><ModelLink page="conteudos" outline>Todas as leituras</ModelLink></div><div className="ni-journal">{content.articles.slice(0, 2).map(article => <article key={article.slug}><Link to={nutritionPath(content.model, 'conteudos/' + article.slug)}><NutritionPhoto image={article.image} alt={article.title}/><span className="ni-eyebrow">{article.category}</span><h3>{article.title}</h3><p>{article.text}</p><span className="ni-text-link">Ler conteúdo →</span></Link></article>)}</div></div></section>
 <section className="ni-section model-faq"><div className="ni-wrap ni-split"><div><span className="ni-eyebrow">Antes de começar</span><h2>PERGUNTAS. CONVERSAS CLARAS.</h2><p>Conheça a proposta de atendimento e como explorar esta experiência.</p><ModelLink page="como-funciona" outline>Como funciona</ModelLink></div><div>{nutritionFaq.map(item => <NutritionFAQ key={item.question} {...item}/>)}</div></div></section>
 <section className="ni-section model-booking"><div className="ni-wrap ni-booking-grid"><div><span className="ni-eyebrow">Seu próximo encontro</span><h2>Vamos conhecer o seu momento?</h2><p>Uma solicitação demonstrativa para experimentar o agendamento. Sem envio de dados ou reserva.</p><p className="ni-note">Use apenas dados fictícios e preferências de contato.</p></div><NutritionBooking model={content.model} services={content.services}/></div></section>
 <section className="ni-section model-contact"><div className="ni-wrap ni-split"><NutritionPhoto image={content.room} alt="Ambiente ilustrativo de consultório de nutrição"/><div><span className="ni-eyebrow">Online e presencial / Modalidades demonstrativas</span><h2>O PRÓXIMO ENCONTRO.</h2><p>Endereço, horários e canais de atendimento a configurar.</p><ModelLink page="contato" outline>Conheça o contato</ModelLink></div></div></section>
 <section className="ni-closing"><div className="ni-wrap"><span className="ni-eyebrow">Uma conversa. Um próximo cuidado.</span><h2>{content.tagline}</h2><ModelLink /></div></section>
 </NutritionLayout>;
}
